### ISSUE TITLE
 int8 quantification

### ISSUE THREAD

**Issue by Qiancj0605** [NVIDIA/TensorRT#1023]
Hi，@ttyio
When doing int8 quantification, how much batch should be used？As shown below：

![image](https://user-images.githubusercontent.com/34846384/105270890-7ab66b80-5bd1-11eb-8eac-b99224df56be.png)

**Comment by ttyio** [comment]
Hello @Qiancj0605, thanks for question.
The batch size is 1 in demoBERT.  And in real case, you can change this value, because the activation histogram is updated after each inference during calibration.  so the calibration result is slight different when using different batch size.  

FYI, We had a GTC session about the int8 in tensorRT, see.
https://on-demand.gputechconf.com/gtc/2017/presentation/s7310-8-bit-inference-with-tensorrt.pdf

**Comment by Qiancj0605** [comment]
Thanks，i get it.
