### ISSUE TITLE
TensorRT Docker Debugging with GDB : Memory Error

### ISSUE THREAD

**Issue by TWJubb** [NVIDIA/TensorRT#1034]
## Description

I am trying to get a debugger (through the CLion IDE) working with a docker container running TensorRT; the image is built with the `nvcr.io/nvidia/tensorrt:20.09-py3` image to match my system. Code runs from the container ok; both from command line compilation and through the IDE; but when I try to add a breakpoint and debug I get

```
com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$GDBCommandException: Warning:
Cannot insert breakpoint 1.
Cannot access memory at address 0x8f1
```

The code I am using is a simple `hello_world.cpp`, and the Dockerfile used is

```
FROM nvcr.io/nvidia/tensorrt:20.09-py3

RUN apt-get update \
  && apt-get install -y ssh \
      build-essential \
      gcc \
      g++ \
      gdb \
      clang \
      cmake \
      rsync \
      tar \
      seccomp \
      python \
  && apt-get clean

RUN ( \
    echo 'LogLevel DEBUG2'; \
    echo 'PermitRootLogin yes'; \
    echo 'PasswordAuthentication yes'; \
    echo 'Subsystem sftp /usr/lib/openssh/sftp-server'; \
  ) > /etc/ssh/sshd_config_test_clion \
  && mkdir /run/sshd

RUN useradd -m user \
  && yes password | passwd user

CMD ["/usr/sbin/sshd", "-D", "-e", "-f", "/etc/ssh/sshd_config_test_clion"]
```

The reason I am posting this issue here is that if I change the base image to `FROM ubuntu:18.04` and repeat the identical steps; everything works and I can step through the code using the CLion debugger as normal. So the only difference being the use of the TensorRT base image.

## Environment

**GPU Type**: 2080Ti
**Nvidia Driver Version**: 450.102.04
**Operating System + Version**: The host system is Ubuntu 18
**Baremetal or Container (if container which image + tag)**:  `nvcr.io/nvidia/tensorrt:20.09-py3`

## Relevant Files

I have some extra verbose logs related to GDB.

## Steps To Reproduce

Starting from the above Dockerfile

```
docker build -t twjubb/basic_clion_test
docker run --privileged --gpus all -d --cap-add=SYS_PTRACE -p=127.0.0.1:2222:22 -p=127.0.0.1:7777:7777 --security-opt seccomp=unconfined twjubb/basic_clion_test
```

Then following the simple CLion tutorial

https://blog.jetbrains.com/clion/2020/01/using-docker-with-clion/

With the`hello_world.cpp` 

```C++
#include <iostream>

int main(int argc, char* argv[])
{
    std::cout << "Hello World" << std::endl;
    return 0;
}
```

and a `CMakeLists.txt`

```
cmake_minimum_required(VERSION 3.10)
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED TRUE)
set(CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}" ${CMAKE_MODULE_PATH})

project(TensorRTCLionTest)
add_executable(hello_world hello_world.cpp)
```

see also 

https://github.com/triton-inference-server/server/issues/679

Which appears to be the same issue; if I repeat the steps mentioned there by `ssh`ing into the container and running `gdb` I get the same memory error as I get through the CLion debugging.

also

https://forums.developer.nvidia.com/t/ngc-pytorch-19-07-and-newer-ubuntu-18-04-gdb-issues/157091

https://github.com/triton-inference-server/server/issues/235

## Simple Steps to Reproduce

To simplify things even further; I can run the container and reproduce the error with the following

```
g++ hello_world.cpp
gdb a.out
break *main
r
```

**Comment by TWJubb** [comment]
I have tried to reduce the problem to the smallest possible size; I can reproduce it with the following steps. 

1. Dockerfile content:

```
FROM nvcr.io/nvidia/tensorrt:20.12-py3
CMD ["/bin/bash"]
```
2. Build and run the container

```
docker build -t twjubb/gdbtest
docker run --privileged --gpus all -it --rm --cap-add=SYS_PTRACE --security-opt seccomp=unconfined twjubb/gdbtest
```

3. Run inside the container;

```bash
apt-get update && apt-get install gdb --y
printf '#include <iostream> \n int main(int argc, char* argv[]){\nstd::cout << "Hello World" << std::endl; \nreturn 0;\n}' >> hello_world.cpp
g++ hello_world.cpp
gdb a.out
break *main
r
```

**Comment by florian-fischer-swarm** [comment]
The same problem also exists in nvcr.io/nvidia/tensorrt:20.11-py3. Right now the image is pretty broken for development :\

**Comment by florian-fischer-swarm** [comment]
Interesting: This problem does not occur if I build the image from the dockerfiles in 
https://github.com/NVIDIA/TensorRT/tree/master/docker

**Comment by theHamsta** [comment]
`set disable-randomization off` solves a similar problem for me in this container.

**Comment by uwydoc** [comment]
same issue here. i happened to find that it is ok to set breakpoint when gdb attach after the process is launched.

ps. you need to set kernel.yama.ptrace_scope to 0 first to allow attach none child process

**Comment by uwydoc** [comment]
after some investigation, i think the problem is caused by the default SHELL, which is `/bin/sh-wrap` (/bin/sh links to sh-wrap).
when gdb` startup-with-shell` is enabled (the default), it launches the target program with `$SHELL -c "exec xxx"`, and gdb assumes that after the first `execv` call, the target program is loaded and ready, which is the case for most (if not all) shells (bash, dash, csh, etc), but not for `/bin/sh-wrap`. what `/bin/sh-wrap` does is call bash (with `execv` call off course) with the same args it receives, basically let bash do the work. so after the first `execv` call, the program launched is actually `bash -c "exec xxx"`, not `xxx` itself, so gdb would failed to figure out(by read `/proc/<child-pid>/mem` file`, btw) the actual memory address to insert breakpoint into based on the static address (acutally offset in the binary) it gets before `run`. in this case, gdb does not prints any warning message (which makes the issue harder to spot at first glance), and just go with the static address, which is quite small (it is an offset anyway) and is obviously not accessible, thus the //Cannot access memory at address// error.
the workaround is quite obivous then, either to disable `startup-with-shell`, or make `/bin/bash` or `/bin/dash` your default shell by set `SHELL` env var, or //fix// the link `/bin/sh` (which i would not recommend)

btw, `/bin/sh-wrap` is quite small and contains only a few instructions, which assembles the `bash ...` command line and call `execv`. but before `execv`, it calls `getenv("_CUDA_COMPAT_STATUS")`, so it seems to have something to do with cuda compatibility library. however, google "sh-wrap" gives NO exact match, which is uncommon. i suspect this file is provided by NVIDIA itself with its cuda container for compatbility purpose to make some gpu-related shell scripts (or installer) happy.

**Comment by nvpohanh** [comment]
Closing for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks

**Comment by theHamsta** [comment]
I observed this issue with some of the Nvidia containers in the past that build on `cuda` base image (seems to be fixed with recent containers for me). Interestingly, lldb would always work where GDB would. Maybe OP can try whether this work around would work on his setup.

**Comment by acmorrow** [comment]
I know this is closed, but I have to add my thoughts here. This `/bin/sh -> /bin/wrap-sh` thing just cost me a crazy amount of time to figure out why I couldn't get tramp to connect into a Triton docker container: it would just hang forever. Since in this case I don't actually care about this container (I'm only using it for compiles), I went ahead and just repointed `/bin/sh` to `/bin/bash`, but there are clearly some deeply deleterious effects of this `wrap-sh` stuff and if the point of this is just to set some `_CUDA_COMPAT_STATUS` I have to wonder why some more traditional mechanism (e.g `/etc/profile`) or similar isn't sufficient. I doubt others are going to figure this out, so I'm also just making this comment to connect the terms emacs, tramp, docker, nvidia, and `wrap-sh` in the hope that it helps others in the future.
