### ISSUE TITLE
How to add plugin python library.

### ISSUE THREAD

**Issue by DonggeunYu** [NVIDIA/TensorRT#1063]
I develop custom layer using c++.
I can convert custom layers with onnx2trt.

But i need to use tensorrt python package to do the conversion.
Any instructions on how to rebuild the TensorRT python package or add a c++ custom layer to tensorrt(python) would be appreciated.

**Comment by ttyio** [comment]
Hello @DonggeunYu , thanks for question.
The python binding is open sourced in https://github.com/NVIDIA/TensorRT/tree/master/python, 

You do not have to rebuild the python binding to add custom plugin in python API, see 
https://github.com/NVIDIA/TensorRT/blob/master/demo/BERT/builder.py#L212
this is sample to add custom plugin in TRT python API.

**Comment by DonggeunYu** [comment]
So, Thank you @ttyio~

**Comment by HuangVictorAuto** [comment]
@DonggeunYu ，
I have the same need as you mentioned, I check the sample from @ttyio ， It has customed a plugin, because the trt already have such "CustomFCPluginDynamic" plugin and api. 
fc_plg_creator = plg_registry.get_plugin_creator("CustomFCPluginDynamic", "1", "")

But how to creat a complete new tensorrt plugin just in Python?
