### ISSUE TITLE
Why the FPS is going down? Could you explain the strange phenomenon?

### ISSUE THREAD

**Issue by liuxb980** [NVIDIA/TensorRT#1223]
### Environment
Dell G3 laptop, GeForce RTX 2060
Ubuntu 20.04
GPU Driver 460.32
TensorRT 7.2.2
Cuda 11.0

The test code is here: [TensorRT_Sample.zip](https://forums.developer.nvidia.com/uploads/short-url/hyv6UFFVbIWi9baWbfBzr4Ud3zK.zip)
run mnist trt model

### Result
(the subtract gpu utility percent is for other processes, and threads in a process are independence.)
1. 1 process，1 thread，total FPS: 28000
FPS: 28000
GPU Utility: 52% - 20% = 32%

2. 1 process，2 threads，total FPS: 23168
FPS: 11589.7 11579.7 
GPU Utility: 45% - 12% = 33%

3. 1 process，4 threads, total FPS: 16608
FPS: 4156.47 4104.48 4161.48 4184.48
GPU Utility: 35% - 16% = 19%

4. 2 processes，2 threads for each，total FPS: 10684
FPS:	2906.56	2932.57	
FPS:    2399.63 2447.61
GPU Utility: 99% - 16% = 83%

### Strange phenomenon
1. 1 process, GPU Utility is low, add threads lead to total FPS decrease, the GPU Utility still is low.
2. 2 processes, GPU Utility is high, but total FPS is very bad.

**Comment by ttyio** [comment]
Hello @liuxb980 ,

we recommend batching over multiple stream in TRT, see https://docs.nvidia.com/deeplearning/tensorrt/best-practices/index.html#batching

I have read your code, and my guessing for your benchmark result is that:
The `cudaEventBlockingSync` would not yield its cpu time slice to other thread, so GPU is starving because of not enough workload input in multi thread mode;
the cpu thread busy waiting lock is partially solved when mutiple process created, each process has its own time slice, that's the reason why GPU utilization raised. The overhead from the GPU context switch, so we get lower FPS. 

You could verify using nsight system to see whats happened here. thanks

**Comment by ttyio** [comment]
Closing since no activities for more than 3 weeks, please reopen if you still have question. Thanks!
