### ISSUE TITLE
how does tensorrt fuse convolution and pooling

### ISSUE THREAD

**Issue by hnuhchen** [NVIDIA/TensorRT#1269]
I'm interested in how tensorrt fuse the convolution op and the pooling op, can you tell me anything about that?

**Comment by ttyio** [comment]
Hello @hnuhchen , the public document is here
https://docs.nvidia.com/deeplearning/tensorrt/best-practices/index.html#enable-fusion
the implementation detail is not opensourced yet.

**Comment by hnuhchen** [comment]
Thank you, do you have a plan for opensource?

**Comment by ttyio** [comment]
@hnuhchen not in near plan yet.

**Comment by hnuhchen** [comment]
thanks

**Comment by twmht** [comment]
@ttyio 

i am trying to fuse slice and convolution together. 

like in shufflenetv2 (https://github.com/ericsun99/Shufflenet-v2-Pytorch/blob/master/ShuffleNetV2.py#L98), since I found out the time in slice is very expensive, this cause shufflenetv2 is even slower than mobilenetv2, the benchmark result is opposed to the paper (https://arxiv.org/abs/1807.11164).

I can create a custom layer to fuse them together, but I can only use cudnn convolution which can not be included in TensorRT autotuning.

Does TensorRT support to call the TensorRT convolution in custom layer? or you have other suggestions for implementing a fuse custom layer?

**Comment by ttyio** [comment]
@twmht , calling cudnn or trt conv in your customer layer still result separate cuda kernels (your kernel and conv kernel). When tensorrt fuse opA and opB, it means opA and opB in the same cuda kernel, no need to write to dram between opA and opB.
