### ISSUE TITLE
Do we have an older version TensorRT(V6.0) in docker for Xavier NX?

### ISSUE THREAD

**Issue by lukezhqin** [NVIDIA/TensorRT#1333]
1,As described in the title, I need to use tensorrt 6.0.1 in docker. I only find docker in amd64 arch~ but how can I get this 6.0Tensorrt in aarch64? 
2,As write in ubuntu-18.04-cross-aarch64.Dockerfile, we use a non-aarch64 "nvidia/cuda:10.0-devel-ubuntu18.04" to build the image. How can I understand this idea then?
Many thanks for your help.

**Comment by galagam** [comment]
Only selected configurations are provided as pre-built docker images.  Consider creating your own, based on [L4T base container](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/l4t-base). 
Please keep in mind that many improvements have been made since TensorRT 6.0.1, and it is highly recommended to use the latest JetPack when working on a Jetson platform.
