### ISSUE TITLE
The same model consumes different sizes of GPU memory in different GPU 

### ISSUE THREAD

**Issue by pengfeidip** [NVIDIA/TensorRT#1334]
**TensorRT：** 7.2.3.4
**GPU:** GTX 1060   RTX 2070 RTX 3060
**OS：**  win10
**CUDA：** 11.1    
**CUDNN：**  8.1 

**Question**
Same model same TensorRT  with win10. 
350MB GPU memory is required with GTX 1060 , 700MB GPU memory is required with RTX 2070 , 1GB GPU memory is required with RTX 3060. 

anyone has the same problem ?

**Comment by pengfeidip** [comment]
I tested the same model, the same software version（TensorRT、CUDA、CUDNN）, consuming 411.25MB on GTX 1060 (6GB) and 416MB on GTX  1080TI (11GB).(Both graphics cards are idle, doing no other work).

Therefore, the architecture of GPU has a great impact on the consumption of GPUmemory？

**Comment by ttyio** [comment]
Hello @pengfeidip ,

For newer arch we would support new unit like tensorCore, this allow us to develop more fancy kernels, sometimes we might need padding the layout when using the tensorCore for better memory access.
Also some new developed kernels would scarify memory for speed, they might not port back to old arch, then we also see higher memory requirement.

**Comment by pengfeidip** [comment]
> Hello @pengfeidip ,
> 
> For newer arch we would support new unit like tensorCore, this allow us to develop more fancy kernels, sometimes we might need padding the layout when using the tensorCore for better memory access.
> Also some new developed kernels would scarify memory for speed, they might not port back to old arch, then we also see higher memory requirement.

- **350 MB** GPU memory is required with GTX 1060 , 
- **1 GB** GPU memory is required with RTX 3060

That's a big difference. Is there any way I can limit GPU memory use for a TensorRT model?

**Comment by ttyio** [comment]
@pengfeidip , we could try setMaxWorkspaceSize to only select the algorithm with less memory requirement.
https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_builder_config.html#aa2f047d415d3c02f1d8126cbd9addc7c

But still we need more memory for newer TRT, because only by create cudnn handle without doing anything there would more memory cost for newer cudnn compare with old cudnn. This can be limited by try setTacticSources to remove cublas, cublasLt, cudnn, but you might fail to build your engine due to missing tactic 
https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_builder_config.html#a37a53d51544307e31a274986ab6dad53

**Comment by pengfeidip** [comment]
> > Hello @pengfeidip ,
> > For newer arch we would support new unit like tensorCore, this allow us to develop more fancy kernels, sometimes we might need padding the layout when using the tensorCore for better memory access.
> > Also some new developed kernels would scarify memory for speed, they might not port back to old arch, then we also see higher memory requirement.
> 
> * **350 MB** GPU memory is required with GTX 1060 ,
> * **1 GB** GPU memory is required with RTX 3060
> 
> That's a big difference. Is there any way I can limit GPU memory use for a TensorRT model?

Thanks. And, please consider the problem of GPU memory consumption in the later version. Such a dramatic change in GPU memory can affect a lot of things.
