### ISSUE TITLE
Is 'ResizeBilinear' OP not supported yet? 

### ISSUE THREAD

**Issue by ginn24** [NVIDIA/TensorRT#138]
Hi! 
It seems that 'ResizeBilinear' operation is not supported yet. 
When will it be solved?

**Comment by jiarenyf** [comment]
Hi!
It seems that 'ResizeBilinear' operation is not supported yet.
When will it be solved?

**Comment by rmccorm4** [comment]
Hi @ginn24,

The UFF parser does not support the ResizeBilinear op. There are no current plans to add more features to the UFF parser. The ONNX parser is more actively being updated instead.

Because of this, tf2onnx (https://github.com/onnx/tensorflow-onnx) and then using TensorRT's ONNX parser is currently the path forward for TensorRT deployment from Tensorflow models.

TF-TRT (https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html) is also supported in case TF->ONNX conversion fails.

**Comment by rmccorm4** [comment]
Closing - Reopen if you are still having a problem.

**Comment by MaybeShewill-CV** [comment]
@rmccorm4 Does tensorrt 4.0.1.6 support resizeBilinear op in an onnx model which in converted from tensorflow model via tf2onxx tool:)

**Comment by MaybeShewill-CV** [comment]
@rmccorm4 
![Screenshot from 2020-04-13 20-26-57](https://user-images.githubusercontent.com/15725187/79120309-291cbd00-7dc5-11ea-9b0a-07167b777b98.png)
