### ISSUE TITLE
fp16 Run Error on T4

### ISSUE THREAD

**Issue by cocorecoco** [NVIDIA/TensorRT#154]
I try to run a caffe  converted model with no plugin on T4 using fp16;
 first I try with fp32 , both  dumping to engine and loading engine for inference successfully  ; but when I try with fp16, dumping to engine is ok ,when loading engine and try to excute , error happend:
`ERROR: ../rtSafe/runnerUtils.cpp (425) - Cudnn Error in safeCudnnAddTensor: 8 (CUDNN_STATUS_EXECUTION_FAILED)./rtSafe/runnerUtils.cpp (ü425) - Cudnn Error in safeCudnnAddTensor: 8`

Anyone knows what happened?

**Comment by rmccorm4** [comment]
Hi @cocorecoco,

This looks like it might be due to version mismatches with CUDA/CUDNN/TensorRT etc.

Check out this related issue: https://github.com/NVIDIA/TensorRT/issues/51#issuecomment-516469198

It looks like upgrading to CUDA 10 resolved this for another user.

To avoid dealing with host-side dependencies, you could also try to use our NGC Docker containers instead: https://ngc.nvidia.com/catalog/containers/nvidia:tensorrt

**Either way, please share your relevant platform information in case other users run into this problem as well:**
Linux distro and version:
GPU type: T4
Nvidia driver version:
CUDA version:
CUDNN version:
Python version [if using python]:
Tensorflow version:
TensorRT version:
If Jetson, OS, hw versions: N/A

**Comment by cocorecoco** [comment]
Linux distro and version: centos 7.3
GPU type: T4
Nvidia driver version: 418.87.01
CUDA version: 10.1.243
CUDNN version: 7.6.3
Python version [if using python]: no
Tensorflow version: no
TensorRT version: 6.0.1.5
If Jetson, OS, hw versions: N/A

**Comment by rmccorm4** [comment]
Hm, that looks like a valid configuration to me (although I believe we only test CentOS 7.5 according the the support matrix: https://docs.nvidia.com/deeplearning/sdk/tensorrt-support-matrix/index.html)

Can you try converting your model using our NGC container: https://ngc.nvidia.com/catalog/containers/nvidia:tensorrt and see if you still get the same error?

You will need to setup nvidia-docker: https://github.com/NVIDIA/nvidia-docker#quickstart

**Comment by rmccorm4** [comment]
Closing since no response.
