### ISSUE TITLE
Dumping INT 8 weights in a file

### ISSUE THREAD

**Issue by Damodharan5** [NVIDIA/TensorRT#156]
Hi,

I am wondering, is there any way to store the INT8 weights of a network in a file ? We have calibration table to store the scales of activations. 

Is there any method to dump the weight_scales and the quantized INT8 weights from TensorRT to a file ?

Thanks in advance,

**Comment by rmccorm4** [comment]
Hi @Damodharan5,

This feature is not available. You can use the `Refitter` API in order to change the weights of a given engine, but you can not retrieve/dump the weights of a given engine. The closest thing is probably dumping the weights from the original model, and saving the calibration cache to reproduce the int8 calibration.

https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/python_api/infer/Core/Refitter.html
