### ISSUE TITLE
RuntimeError: No Op registered for Range with domain_version of 10

### ISSUE THREAD

**Issue by zang5xixi** [NVIDIA/TensorRT#1658]
i am trying to convert a pytorch model which uses ```torch.arange``` in the code to onnx and encounter such a issue
```
RuntimeError: No Op registered for Range with domain_version of 10
```
it means that ```opset_version=10``` does not support the operator ```arange```.But when i change the version to ``` opset_version=11```, i encounter another issue:
```
In function importPad: [8] Assertion failed: inputs.at(1).is_weights()
```
any adivice?

**Comment by zerollzeng** [comment]
1.  range op only support in opset 11, see https://github.com/onnx/onnx/blob/master/docs/Operators.md#Range

2. TensorRT requires range op's inputs must be initializer(Floating point inputs are only supported if start, limit, and delta inputs are initializers), see https://github.com/onnx/onnx-tensorrt/blob/master/docs/operators.md

**Comment by zang5xixi** [comment]
> 1. range op only support in opset 11, see https://github.com/onnx/onnx/blob/master/docs/Operators.md#Range
> 2. TensorRT requires range op's inputs must be initializer(Floating point inputs are only supported if start, limit, and delta inputs are initializers), see https://github.com/onnx/onnx-tensorrt/blob/master/docs/operators.md

Hi,
```
import torch
import torch.nn as nn
import torch.nn.functional as F

class TestModule(nn.Module):
    def __init__(self):
        super(TestModule, self).__init__()

    def forward(self, x, lengths, tensor):
        x = F.pad(x, (0,0,1,1), mode="constant", value=0)
        return x
        

input1 = torch.randn([2, 10, 2])

model = TestModule()
model.eval()
torch.onnx.export(model, input1, 'test.onnx', verbose=True, opset_version=11, input_names=['input1'], output_names=['output'])
```
Here is my code.  Can you help me point out where the mistake is？Thanks~

**Comment by nvpohanh** [comment]
@zang5xixi With your code, I am getting this error in TRT:

```
[shuffleNode.cpp::symbolicExecute::387] Error Code 4: Internal Error (Reshape_3: IShuffleLayer applied to shape tensor must have 0 or 1 reshape dimensions: dimensions were [-1,2])
```

![2022-06-15 16_51_03-__dc2-cdot74-scr02_scratch pohanh_sw_TensorRT-debug_build_tensorrt-base-dev_rel-](https://user-images.githubusercontent.com/53919306/173786050-84a806a7-3c1c-458f-bd41-d3a0f2436119.png)

This is because the generated ONNX model uses a ton of ops just to compute the padding sizes, which are very unnecessary. Therefore, I sanitized the ONNX file using: `polygraphy surgeon sanitize -o build/test_pad_sanitized.onnx --fold-constants build/test_pad.onnx` and now the ONNX file becomes cleaner and it can now run through TRT.

![2022-06-15 16_51_38-__dc2-cdot74-scr02_scratch pohanh_sw_TensorRT-debug_build_tensorrt-base-dev_rel-](https://user-images.githubusercontent.com/53919306/173786079-a01e4c1f-156b-40dd-be06-fc57c2df00c6.png)

I am going to close this issue for now. Please feel free to reopen if the issue still exists. Thanks
