### ISSUE TITLE
Can not both import tensorrt and torch

### ISSUE THREAD

**Issue by feiyuhuahuo** [NVIDIA/TensorRT#1693]
## Description
import tensorrt or import torch alone works well. But if import tensorrt first and then import torch, it comes with error.

```
>>> import tensorrt as trt
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\feiyuhuahuo\python_base\lib\site-packages\torch\__init__.py", line 124, in <module>
    raise err
OSError: [WinError 127] 找不到指定的程序。 Error loading "C:\Users\feiyuhuahuo\python_base\lib\site-packages\torch\lib\cublas64_11.dll" or one of its dependencies.
```
## Environment

**TensorRT Version**: 8.2.2.1
**NVIDIA GPU**: RTX2080 super max-Q
**NVIDIA Driver Version**: 496.13
**CUDA Version**: 11.5
**CUDNN Version**: 11.3
**Operating System**: win10
**Python Version (if applicable)**: 3.9.6
**Tensorflow Version (if applicable)**: None
**PyTorch Version (if applicable)**: 1.9.0
**Baremetal or Container (if so, version)**: None

## Steps To Reproduce
Only two lines:
```
import tensorrt as trt
import torch
```

**Comment by zerollzeng** [comment]
Try change the import order
```
import torch
import tensorrt as trt
```

**Comment by Pong-97** [comment]
你好，我也碰到了相同问题。在更换了torch和trt的import顺序之后，反而出现了新的问题（大概是一个.ddl出问题）。请问你的问题解决了吗？

**Comment by andrearosasco** [comment]
This interference happens with other packages too. Sometimes it's hard to find an order of imports that work.
I had to create some objects at the top level before some of the imports to make it work because the imports in the files where those classes were defined were causing problems.

**Comment by feiyuhuahuo** [comment]
Has this problem been solved?

**Comment by Pong-97** [comment]
Sorry, the problem remains发自我的iPhone------------------ Original ------------------From: Slark  ***@***.***>Date: Wed,Apr 20,2022 11:04 AMTo: NVIDIA/TensorRT ***@***.***>Cc: Pong-97 ***@***.***>, Comment ***@***.***>Subject: Re: [NVIDIA/TensorRT] Can not both import tensorrt and torch (Issue#1693)
Has this problem been solved?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/NVIDIA/TensorRT/issues/1693#issuecomment-1103422871",
"url": "https://github.com/NVIDIA/TensorRT/issues/1693#issuecomment-1103422871",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by irexyc** [comment]
@[feiyuhuahuo](https://github.com/feiyuhuahuo) I think your OSError problem is due to the different cuda version of your C:\Users\feiyuhuahuo\python_base\lib\site-packages\torch\lib\ and C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.x.
When your import tensorrt, it will load soma cuda dll from NVIDIA GPU Computing Toolkit, while the torch load dll from torch/lib, you can check this.

While even if I hide the  NVIDIA GPU Computing Toolkit path from system and add torch/lib in the PATH to let the tensorrt load dll from torch/lib, I also meet some problems.

Don't know if this problem only happens on windows.

**Comment by feiyuhuahuo** [comment]
I updated PyTorch version to 1.11, and it's OK now. I tested different environments. WIN10 + PyTorch1.11 + CUDA11.5 + tensorrt8.2.4 is OK. UBUNTU20.04 + PyTorch1.11 + CUDA11.5 + tensorrt8.2.4 is OK.

**Comment by wangtianlong1994** [comment]
I had the opposite problem, I would report an error if I first import torch and then import tensorrt, and eventually I found the problem, don't use pip to download the pytorch gpu version, use conda to download the pytorch gpu version works well

**Comment by nvpohanh** [comment]
Closing this for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks!
