### ISSUE TITLE
Build not generating libnvinfer.so?

### ISSUE THREAD

**Issue by ysyyork** [NVIDIA/TensorRT#1750]
## Environment

**TensorRT Version**: 8.2 GA
**NVIDIA GPU**: 2080 Ti
**NVIDIA Driver Version**: 460
**CUDA Version**: 11.2
**CUDNN Version**: 
**Operating System**: ubuntu 18.04
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

I'm trying to do cross compilation for my jetson NX (running jetpack 4.6) with TRT 8.2. I followed the README about cross compilation using docker with a host machine with the above environment. it builds well and generated the below files:
![image](https://user-images.githubusercontent.com/6693605/150759586-2b03c08a-c0fe-4521-807b-b8b8eea14bc8.png)

Then I'm following the post here https://docs.nvidia.com/metropolis/TLT/tlt-user-guide/text/instance_segmentation/mask_rcnn.html#tensorrt-open-source-software-oss and replaced the files on my jetson with the built files and wishing it could resolve the issue listed here: https://github.com/NVIDIA/TensorRT/issues/1654 However, I got the same issue about the 1D Transpose layer issue when I run trtexec to convert my onnx model to trt engine. 

as I noticed, the generated file doesn't include libnvinfer.so.8.2.1, however on jetson, in the `/usr/lib/aarch64-linux-gnu` folder, I do see currently it's still `libnvinfer.so.8.0.1`. Below are all the files after I copied to jetson under the folder:
![image](https://user-images.githubusercontent.com/6693605/150761178-44b29fbb-0e61-4d96-900c-804e89994080.png)

Then I did another quick test intending to see if this is the cause of the issue. I pulled the image here `nvcr.io/nvidia/tensorrt:21.12-py3` to my host linux machine (not the jetson) and as the release note mentioned, this one is equipped with trt 8.2.1. Then I run the `trtexec` to convert the same onnx model in this container, it works. The 1D Transpose error wouldn't show up. Then I checked the library files and see the `libnvinfer.so` version is 8.2.1
![image](https://user-images.githubusercontent.com/6693605/150761907-1df9c83e-f798-477b-ba52-4d5954208c35.png)

My question here is, how I can install this lib alone on jetson (or build from source). I also build an x86_64 version for this TRT OSS and the output also didn't include this file. I'm assuming it's not within TRT OSS? I'm searching online but couldn't find any place that teaches me how to build that file alone. Instead it's all letting me install the TRT dpkg package from release files which includes everything but can't work on jetson.

**Comment by ysyyork** [comment]
Hmm i think i got it, actually the libnvinfer.so file is in the /pdk_files folder from the jetpack libraries. It seems I have to wait for jetpack to support trt8.2 until I can build from scratch. But this is like a dead loop :(  I want to build because I don't want to wait for jetpack to release lol

**Comment by austingg** [comment]
libnvinfer.so is one part of TensorRT SDK, not generated by this repository, which is TensorRT-OSS

**Comment by wraveane** [comment]
If I understand correctly, the problem mentioned in the other issue was related to ConvTranspose not being parsed properly by the TRT ONNX parser. The ONNX parser library, however, can be built directly via this repository, so you can try that as a quicker solution, while still using TRT 8.0.

One of the files your build generated was `libnvonnxparser.so.8.2.1`. This library _should_ be compatible with TRT 8.0 on your Jetson. As I noticed from your screenshot of your `/usr/lib/aarch64-linux-gnu` directory, this file is already there, as you already had copied it. But very important, also make sure that the symlink originally pointing `libnvonnxparser.so.8 -> libnvonnxparser.so.8.0.1` is now pointing to the new `libnvonnxparser.so.8.2.1` version instead, as this symlink is what TRT will link to.

If all is done properly, your model should now be parsed correctly, even in TensorRT 8.0. Assuming of course the bug was only with the ONNX parser.

**Comment by nvpohanh** [comment]
> Do you found a way to compile libnvinfer.so from source ?

We don't release the source code of libnvinfer.so. You will need to install it from: https://developer.nvidia.com/nvidia-tensorrt-download

**Comment by nvpohanh** [comment]
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks
