### ISSUE TITLE
PointPillar int8 in Jetson AGX Xavier

### ISSUE THREAD

**Issue by ShallowMDream** [NVIDIA/TensorRT#1762]
Environment:
TensorRT Version: 7.1.3.0 (jetpack4.4 default)
CUDA Version: 10.2 (jetpack4.4  default)

Description:
I'm trying to infer PointPillar  from fp16 to int8  on Xavier.
I have found the fp16's speed similar int8.After using nsys to show:
![nsys](https://user-images.githubusercontent.com/35364227/151319847-f76b2a3d-31ce-44fe-b5fb-2fad09f3cd9c.png)
I know the reformatter means fp-in->int8-out.
And my question is why all ops are not int8? if can do, what should Ido?

Thanks.

**Comment by galagam** [comment]
TensorRT will choose a higher precision kernel if an implementation with the precision you've selected is not available, or if using it results in a higher overall runtime on the device (i.e. due to added reformatting). 
In any case, I would recommend upgrading to a more recent [JetPack](https://developer.nvidia.com/embedded/jetpack) version.
