### ISSUE TITLE
CMake Error at CMakeLists.txt:128 (find_library_create_target):   find_library_create_target Macro invoked with incorrect arguments for macro   named: find_library_create_target

### ISSUE THREAD

**Issue by sainttelant** [NVIDIA/TensorRT#1857]
my enviroment ubuntu18.04
tensorrt8.2 GA
cuda11.2

find_library_create_target    invoked with incorrect arguments for macro, ,any ideas?

**Comment by ttyio** [comment]
@sainttelant , have you tried build using container?
https://github.com/NVIDIA/TensorRT/tree/release/8.2#setting-up-the-build-environment
thanks

**Comment by sainttelant** [comment]
@ttyio ,   thanks you very much, i 've tired to replace macro define with function define in CMakelist, and it worked well, i have no idea why my system couldn't recognize the Macro definition in Cmakelist, weired!

**Comment by sainttelant** [comment]
anyway,  if someone had the similar issues with me, just trying to USE function to subsitute it.

**Comment by frankvp11** [comment]
How did you solve it? I'm confused at to what you did? @sainttelant

**Comment by chavinlo** [comment]
If anyone has this issue, you are most likely missing the TRT_LIB_DIR argument or it's empty on `/CMakeLists.txt`.

```
find_library_create_target(nvinfer nvinfer SHARED ${TRT_LIB_DIR})
find_library_create_target(nvuffparser nvparsers SHARED ${TRT_LIB_DIR})
```

You can check this by adding the following line before calling `find_library_create_target`
`message( STATUS "TRT_LIB_DIR: ${TRT_LIB_DIR}")`

Then try running again, if it prints something like `TRT_LIB_DIR:` and nothing after that then that's why

The TRT_LIB_DIR should point to... well the tensorrt lib path: https://github.com/NVIDIA/TensorRT/blob/main/README.md#optional---if-not-using-tensorrt-container-specify-the-tensorrt-ga-release-build-path

However if you installed tensorrt via `apt` (like me) then run `find / -name "libnvinfer.so*"` and it will return something like this:
```
(env) root@92fb855941e1:~/TensorRT-8.6.1.6/lib# find / -name "libnvinfer.so*"
/root/env/lib/python3.10/site-packages/tensorrt_libs/libnvinfer.so.8
/usr/lib/x86_64-linux-gnu/libnvinfer.so.8.6.1
/usr/lib/x86_64-linux-gnu/libnvinfer.so
/usr/lib/x86_64-linux-gnu/libnvinfer.so.8
```
In this scenario `/usr/lib/x86_64-linux-gnu/` is what I should point TRT_LIB_DIR to, so I ran `export TRT_LIBPATH=/usr/lib/x86_64-linux-gnu/`, then 
```
cmake .. -DTRT_LIB_DIR=$TRT_LIBPATH -DTRT_OUT_DIR=`pwd`/out
``` 
and it worked.

Finally, what @sainttelant was referring to (I believe) was to change `macro` for `function` in `cmake/modules/find_library_create_target.cmake` both at start and end. like this:

```cmake
function(find_library_create_target target_name lib libtype hints)
...
endfunction()
```
