### ISSUE TITLE
size() of BufferManager is acutually nbBytes()

### ISSUE THREAD

**Issue by daquexian** [NVIDIA/TensorRT#196]
## Description

The [method](https://github.com/NVIDIA/TensorRT/blob/master/samples/common/buffers.h#L312) named "size" returns "nbBytes" of a buffer.

However, there is [another method](https://github.com/NVIDIA/TensorRT/blob/master/samples/common/buffers.h#L129) named "size" that returns element nums instead of bytes of a buffer.

It can lead to confusing bugs. It will be better to rename the first method to "nbBytes".

**Comment by daquexian** [comment]
@rmccorm4 If this is a valid issue, I'm willing to propose a PR. I'm looking forward to your reply :)

**Comment by rmccorm4** [comment]
Hi @daquexian,

I see what you mean and it seems like a simple enough request, but given that it's more of a common function that is used internally for the samples rather than the public-facing API, I'm not sure it's worth changing in all of the locations that the function gets called.

Because then you'll have to go test all of the samples again just to make sure the find+replace didn't accidentally break anything just for a name change instead of a functionality change :confused: 

If it were an API method, that would potentially cause more trouble.

**Comment by daquexian** [comment]
@rmccorm4 Thanks, you are right~

**Comment by rmccorm4** [comment]
Thanks for understanding 🙂

**Comment by daquexian** [comment]
@rmccorm4 I think it's still a valid issue, It's not fixable just due to practical reason, so it should remain open. What's your opinion? :)

**Comment by rmccorm4** [comment]
> it's not fixable just due to practical reason

Since this likely won't be fixed, I'd rather not keep it open at the moment. Perhaps it can be re-opened down the line or a new issue can be opened if it comes up again.

It's just easier to maintain the issues this way, keeping issues that **will be fixed but aren't yet solved** open as a pseudo TO-DO list
