### ISSUE TITLE
windows TensorRT inference time  fluctuates greatly

### ISSUE THREAD

**Issue by wang7393** [NVIDIA/TensorRT#1977]
## Description
windows TensorRT inference time (enqueueV2) fluctuates greatly,  as fllows
![QQ截图20220512111259](https://user-images.githubusercontent.com/29936604/167985093-70da010f-1ce0-4ec5-bb9d-88f7e0316532.png)

## Environment

**TensorRT Version**:  8.4.0.6
**NVIDIA GPU**:  T600
**NVIDIA Driver Version**:  511.65
**CUDA Version**: 11.6
**CUDNN Version**: 8.x
**Operating System**:  win10
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by nvpohanh** [comment]
Could you share your code about how you measure the latency? If you are using cudaEventSynschronize(), please make sure that the cuda event is created with cudaEventDefault flag instead of cudaEventBlockingSync flag. 

Compare to Linux, Windows tends to have worse context switching overhead and sometimes a sleeping CPU thread cannot be waked up immediately.

**Comment by wang7393** [comment]
@nvpohanh  the test code as fllows, But I used the same code to test with the Win10-Ubuntu subsystem, and the inference time still fluctuated wildly
` auto time_2 = std::chrono::high_resolution_clock::now();`
`bool status = m_context->executeV2(m_buffers->getDeviceBindings().data());` 
`auto time_3 = std::chrono::high_resolution_clock::now();`
`std::chrono::duration<double, std::milli> dElapsedTime_2 = (time_3 - time_2);`
`printf("enqueueV2:%f\n", dElapsedTime_2.count());`

**Comment by nvpohanh** [comment]
Closing due to no response for >14days. Please feel free to reopen if the issue still exists. Thanks
