### ISSUE TITLE
Can I use A10 env compile/optimize a model and run the plan on T4

### ISSUE THREAD

**Issue by cszhz** [NVIDIA/TensorRT#2001]
Hello
I want to compile a model and run it in a different environment.
In TVM, I can use "target" parameter
I just want to know if I  use A10 environment compile/optimize a model, can I run the plan on T4?

thanks.

**Comment by zerollzeng** [comment]
TVM is kind of off-topic here :-).

Yes for the TVM compiled.so. because it just contains the TRT networks(not built yet)
e.g.
with tvm.transform.PassContext(opt_level=3, config={'relay.ext.tensorrt.options': config}):
    lib = relay.build(mod, target=target, params=params)

can be exported on an A10 env and loaded on T4. but please make sure the TRT version you are using for the 2 cards is the same. 

and NO for the TRT engine, if you've built the engine on A10, then you can use it in T4, it's not compatible or may have perf regression.

**Comment by cszhz** [comment]
thank you for quick response.
Actually I go through the API document and don't find such functionality.
