### ISSUE TITLE
int8 accuracy ResNet50

### ISSUE THREAD

**Issue by harishprabhala** [NVIDIA/TensorRT#2028]
I have converted the ResNet50 to int8 using ResNet50 calibration cache. Although there has been an increase in inference speed, I'm not able to quantify the accuracy. Is there a Python code to evaluate the accuracy of int8 converted models in TensorRT?

**Comment by azhurkevich** [comment]
@harishprabhala you can look at eval_coco.py and infer.py in both [tensorflow object detection](https://github.com/NVIDIA/TensorRT/tree/main/samples/python/tensorflow_object_detection_api) and [detectron 2](https://github.com/NVIDIA/TensorRT/tree/main/samples/python/detectron2) examples. As soon as you've built and int8 engine for inference purposes it should be treated the same way as fp32/16 would. Since you have ResNet50, most likely it is just a classification not an object detection like in examples I've sent, so you would want to ignore object detection part specifically. Most important concepts to run trt inference with python are in those examples. Please reach out if you have any further questions.

**Comment by harishprabhala** [comment]
Thanks @azhurkevich. I'll give it a try.
