### ISSUE TITLE
Low performance after a delay

### ISSUE THREAD

**Issue by dany137718** [NVIDIA/TensorRT#2042]
Hi,
I'm trying to infer ONNX model on RTX 3070.
I infer once and wait for 10 seconds and retry 10 times, this is the result :

![image](https://user-images.githubusercontent.com/37046269/172578468-cf6e9fcc-a357-4470-a35d-c56608440c07.png)

after 10 sec time for a one infer is 92ms!
and after a while, it will be ok. 
if I use this model continuously, I never see this problem, but I receive very latency with a delay. 
what should I do about this problem? 
best regards.

**Comment by nvpohanh** [comment]
@dany137718 Are you using Windows or Linux OS?

Regardless of which one, this is typically caused by GPU clock frequency. Could you try locking the GPU lock at maximum using `sudo nvidia-smi -lgc <freq>` where the supported clock freq can be found by `nvidia-smi -q -d SUPPORTED_CLOCKS`?

**Comment by dany137718** [comment]
> 

thanks for your reply,
I'm using Windows and c++ Programming Language.
i use this code `nvidia-smi -q -d SUPPORTED_CLOCKS` and this is the result:

![image](https://user-images.githubusercontent.com/37046269/172585642-628ac22e-4680-45d1-85a3-3bb880aa7174.png)

which one should I use?

**Comment by nvpohanh** [comment]
`sudo nvidia-smi -lgc 2160` try this? If it says your GPU doesn't support this, then try `sudo nvidia-smi pm 1 && sudo nvidia-smi -ac 7001,2160`.

**Comment by dany137718** [comment]
i use this code `sudo nvidia-smi -lgc 2160` and this is the result : 

![image](https://user-images.githubusercontent.com/37046269/172589548-8f86c363-7735-47b5-9a61-514ee89a7bc9.png)

i use this code `sudo nvidia-smi -lgc 7001` and this is the result : 

![image](https://user-images.githubusercontent.com/37046269/172590338-b1e70de0-adbc-4ca0-8f3f-7a1b3ac77acf.png)

wow, it is much better, can I fix that 34ms and change it to 13ms?
I use this code on GTX 750 ti and I cant see this problem.

**Comment by dany137718** [comment]
in GTX 750 ti I hadn't any Cuda engine in task manager so my model load on compute_0 engine. 
in this RTX 3070, I have a Cuda engine, and my model load on this engine.

this is the RTX 3070's task manger : 

![image](https://user-images.githubusercontent.com/37046269/172592031-36a76dd5-c3ad-4bc5-916e-c1b9ed231715.png)

**Comment by nvpohanh** [comment]
Could you share the output of `nvidia-smi -q`? This doesn't look like a TRT issue, but a CUDA driver issue. The best guess is that after a few seconds of being idle, the driver (or the Windows OS) puts the GPU to idle and it takes a while for the GPU to be waken up and boosted to the max performance mode. If this guess is true, then there is nothing we can do to improve it further.

Do you connect the GPU to a display? Maybe try connecting the display to another GPU so that this GPU can focus on computation work?

**Comment by dany137718** [comment]
this is result of `nvidia-smi -q` : [nvidia-smi -q result.txt](https://github.com/NVIDIA/TensorRT/files/8860687/nvidia-smi.-q.result.txt)

I haven't any on board display port :( .

**Comment by nvpohanh** [comment]
Unfortunately, I don't think there is much we can do to further improve the performance, partially because this is a GeForce-brand GPU. For Tesla/Quadro GPUs, you will have more options like enabling the Persistence Mode or setting the GPUs to TCC mode from WDDM mode so that GPUs can be configured to always be in max-performance mode even if there is no active workload.

If it is really caused by the WDDM mode, then using Linux OS will improve it to some extent.

**Comment by dany137718** [comment]
> Unfortunately, I don't think there is much we can do to further improve the performance, partially because this is a GeForce-brand GPU. For Tesla/Quadro GPUs, you will have more options like enabling the Persistence Mode or setting the GPUs to TCC mode from WDDM mode so that GPUs can be configured to always be in max-performance mode even if there is no active workload.
> 
> If it is really caused by the WDDM mode, then using Linux OS will improve it to some extent.

ok, thanks a lot. that clock increase makes my fps better. 
I try to search for a solution to set max-performance mode. 
thank you a lot for your time 💯

**Comment by dany137718** [comment]
hi again!
finally, it worked! 
1. I set GPU clock frequency at maximum with  `nvidia-smi -lgc 7001`
2. in Nvidia Control Panel -> manage3D Setting set this parameter:
      Power Mangment Mode -> Prefer max performance
      Low Latency Mode -> Ultra

and tada! worked ! this is result : 

![image](https://user-images.githubusercontent.com/37046269/172783717-9f3959bf-aaff-4a07-be77-1e669f67debb.png)

Thanks!
I close this issue.
