### ISSUE TITLE
TensorRT Docker images cannot install ngc

### ISSUE THREAD

**Issue by zacool64** [NVIDIA/TensorRT#2057]
## Description

While building the ubuntu 20.04 Dockerfile for TensorRT, I encountered the following error which never occurred for me prior to today:
```
chmod: cannot access 'ngc': No such file or directory
The command '/bin/bash -c cd /usr/local/bin && wget https://ngc.nvidia.com/downloads/ngccli_cat_linux.zip && unzip ngccli_cat_linux.zip && chmod u+x ngc && rm ngccli_cat_linux.zip ngc.md5 && echo "no-apikey\nascii\n" | ngc config set' returned a non-zero code: 1
```

It looks like a new version of ngc-cli was released recently, and the existing docker images are out-of-date.

## Environment

**TensorRT Version**: 8.2.5.1
**NVIDIA GPU**: Tesla T4
**NVIDIA Driver Version**: 470.57.02
**CUDA Version**: 11.4.2
**CUDNN Version**: 8
**Operating System**: Ubuntu 20.04
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: Container; building `ubuntu-20.04.Dockerfile` associated with the 22.06 release

## Steps To Reproduce

1. Clone the latest version of this repository
2. Invoke `./docker/build.sh` to begin building the image. I was able to reproduce without modifying any of the parameters.

**Comment by zerollzeng** [comment]
@rajeevsrao ^ ^

**Comment by rajeevsrao** [comment]
@zacool64 this is fixed on main and release/8.4 (posted today). For release/8.2 branch here is the cherry-pick: https://github.com/NVIDIA/TensorRT/pull/2059

**Comment by rajeevsrao** [comment]
@zacool64 fix has been merged on release/8.2 branch as well. Please verify at your end and let us know. Thanks.

**Comment by zacool64** [comment]
Can confirm, this is fixed now.

**Comment by okhonko** [comment]
@rajeevsrao
I faced same issue when building TensorRT-OSS by following README instructions and running
`./docker/build.sh --file docker/ubuntu-20.04.Dockerfile --tag tensorrt-ubuntu20.04-cuda11.8`


I noticed that in [instructions](https://github.com/NVIDIA/TensorRT#download-tensorrt-oss) `master` branch of `TensorRT` is being cloned. 
But fix https://github.com/NVIDIA/TensorRT/pull/2059 is not present in `master` branch: https://github.com/NVIDIA/TensorRT/blob/master/docker/ubuntu-20.04.Dockerfile#L92 . The fix is present in `main` and some release branch. I also noticed that `master` branch wasn't updated for a long time.

Should instructions be updated to use `main` branch instead?
Or should https://github.com/NVIDIA/TensorRT/pull/2059 fix also be applied to `master` branch?
