### ISSUE TITLE
Myelin error when load ONNX model, Assertion `false && "Invalid size written"' failed

### ISSUE THREAD

**Issue by jacker-whh** [NVIDIA/TensorRT#2068]
## Description
We’re preparing to use Orin with TensorRT8.3 for better performance, but it failed when creating a Builder. Error occurred in myelin which is close-sourced, we’ve gotten stuck here for days and had no clue where to start debugging, so ask for your help:)

## Environment
**TensorRT Version tensorrt 8.3:
**GPU Type Orin:
**Nvidia Driver Version 515:
**CUDA Version 11.4:
**CUDNN Version 8.2:

## Relevant Files
onnx:
https://drive.google.com/file/d/11UreFcd_bZZIOubgti06ysY2ZF6S48uM/view

error-log:
https://drive.google.com/file/d/1Qkb93Th_mGCaLlonysp5M07At69aA5Sl/view

## Steps To Reproduce
trtexec --onnx=swin_tiny_patch4_window7_224_opt.onnx --workspace=4096 --int8 --verbose --saveEngine=swin_tiny_patch4_window7_224_opt.trt

**Comment by zerollzeng** [comment]
I can't reproduce this in 8.4. can you try the latest version?

**Comment by duanshengliu** [comment]
Hi, I've encountered a similar error during the conversion of onnx to trt in the last two days, my two onnx models all contain LSTM op. I refer to https://github.com/NVIDIA/TensorRT/issues/1928 (which is consistent with my error message). According to jackwish's description, I think there is no **libcublas.so** or **libcublasLt.so** in the path of **/usr/local/cuda/lib64**, although there are **libcublas.so.11** and **libcublasLt.so.11** in  this path. So jackwish's solution is to create a soft link, but since I don't have sudo privileges to execute:
```
sudo ln -s libcublas.so.11 libcublas.so
sudo ln -s libcublasLt.so.11 libcublasLt.so
sudo ldconfig
```
I thought of an other and successfully solved the problem:
```
cp /usr/local/cuda/lib64/libcublas.so.11 /path/to/your/tensorrt/lib/libcublas.so
cp /usr/local/cuda/lib64/libcublasLt.so.11 /path/to/your/tensorrt/lib/libcublasLt.so
```
I assume you have added /path/to/your/tensorrt/lib to the environment like this: 
```
export LD_LIBRARY_PATH=/path/to/your/tensorrt/lib:$LD_LIBRARY_PATH
export LIBRARY_PATH=/path/to/your/tensorrt/lib:$LIBRARY_PATH
source ~/.bashrc
```
I found out that my error was actually due to the lack of **libcublasLt.so**. Hope my method works for you！@[jacker-whh](https://github.com/jacker-whh)

**Comment by jacker-whh** [comment]
Thanks, it has been solved

**Comment by jacker-whh** [comment]
> I can't reproduce this in 8.4. can you try the latest version?

Thank you, is your orin platform? Where to install 8.4? My problem has been solved downstairs
