### ISSUE TITLE
demo BERT max_batch_size dont work 

### ISSUE THREAD

**Issue by taomiao** [NVIDIA/TensorRT#212]
## Description

```bash
python bert_builder.py \
    -m bert/bert_language_model_tf/model.ckpt \
    -o bert_128_32.engine \
    -b 8 \
    -s 128 \
    -c bert/bert_language_model_tf
```
```
E1111 13:11:24.493515 1430 model_repository_manager.cc:813] failed to load 'bert_trt_zh_top20_b32' version 1: Invalid argument: unexpected configuration maximum batch size 8 for 'bert_trt_zh_top20_b8' profile [], model maximum is 1
```

## Environment

**TensorRT Version**: 6.0.1
**GPU Type**: titan xp
**Nvidia Driver Version**: 418.56
**CUDA Version**: 10.1
**CUDNN Version**: 
**Operating System + Version**: 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: 

## Steps To Reproduce

just follow the demo/BERT/python README.md ， change "-b 1" to "-b 8"

**Comment by rmccorm4** [comment]
Hi @taomiao,

Can you provide the full traceback/error? 

1. It looks to me like you're using TensorRT Inference Server. If so, you didn't include the commands that you're running to start the server and send inference requests

2. This model uses optimization profiles. If you look at the code here: https://github.com/NVIDIA/TensorRT/blob/master/demo/BERT/python/bert_builder.py#L343-L355, there are 3 optimization profiles created. Batch size of 1, Batch size from the `-b <batch_size>` flag (in this case 8), and then Batch size of 8. When doing inference, I believe you have to choose the optimization profile, otherwise the first profile is used by default. In this case, the first profile is batch size of 1, which is why your error shows `model maximum is 1`, because the first optimization profile can only do batch size of up to 1.

You need to choose the optimization profile to use when doing inference at runtime: https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#opt_profiles

To use the second optimization profile corresponding to the `-b` flag you pass in, you need to set that.

C++
```cpp
context.setOptimizationProfile(1)    # Second profile == batch size from -b flag
```

Python
```python
context.active_optimization_profile = 1     # Second profile == batch size from -b flag
```

**Comment by taomiao** [comment]
@rmccorm4 thanks , you solve my problem.
