### ISSUE TITLE
i just want to known when to use trt api and use onnx if all of them can be work…

### ISSUE THREAD

**Issue by blazeCCC** [NVIDIA/TensorRT#2183]
Could someone tell me what a difference in build with tensort api and build with onnx? When i test in 2d net work, the speed of them seem to be same and the speed in 3d point clound network may be some different. I like to build net work with tensorRT api but i don’t know whether it has some advantage than onnx.Thanks!.i just want to known when to use trt api and use onnx if all of them can be work…

**Comment by jackwish** [comment]
In general, if ONNX parser works for you, you don't need to build with TensorRT API since that might take you some time to finish as you need to understand the semantic of the APIs.

Sometimes, API programming might have better performance and engineering benefits.
* For performance, some ONNX models contains subgraph that can be optimized out while TensorRT might not cover yet. For example, consider there is `Mul(1, tensor)` in ONNX model which equals to `tensor` semantically, you can skip the Mul with API). This problem is due to the ONNX exporters generate some unneeded ops.
* For engineering benefits, API gives you fine grain control over the network while the parser doesn't. For example, it would be easier to dump the output of an activation (mark it as output), also easier to setup precision per layer.

Closing as this is a QA. Feel free to reopen if any further question.

**Comment by blazeCCC** [comment]
> 

thank you! I basically get it.
