### ISSUE TITLE
Is there any pre-requests for applying myelin when building trt engine?

### ISSUE THREAD

**Issue by Jiang-Stan** [NVIDIA/TensorRT#2323]
## Description

Hi,
I wrote a custom plugin for TensorRT, hoping to benefit from QDQ fusion. I manually fused QDQ with custom plugin as suggested in https://github.com/NVIDIA/TensorRT/issues/2283. But when visualizing model by trt-engine-explorer, I found that myelin is not applied to any parts of my model, which lead to serious speed degragation. Although myelin is a non-opensource backend, could you please tell us if any pre-requests should be satisfied to make it in use? does it need QDQ in pair?

Thanks a lot in advance!

**Comment by zerollzeng** [comment]
Myelin only optimizes the sub-graph with specific parttern(e.g. multi-head attention in Transformer based network or some point-wise operations), and it only supports models with QDQ(not support PTQ) so I think it doesn't relate to your QDQ fusion. @jackwish correct me if I'm wrong :-)

Do you have a screenshot on how your network looks like?

**Comment by jackwish** [comment]
@Jiang-Stan Thank you for reporting this issue! Could you please share details about why "myelin is not applied to any parts of my model, which lead to serious speed degragation"?

**Comment by Jiang-Stan** [comment]
TRT engine built with official DeiT with QDQ inserted is shown below:
![qDeiT onnx engine graph json](https://user-images.githubusercontent.com/74638604/190056561-b738f8a8-bb81-4426-a2aa-e5c099ff6ed6.svg)

It seems that all the transformer layers are packaged as a single Foreign Node by Myelin. (Here is a question, how could I know whether Myelin applied int8 or not?) 

But when I replace softmax with my own manually fused DQ-IntSoftmax-Q plugin, and replace qkv-Linear+gather by detached q-Linear+k-Linear+v_Linear(since model with Gather would report error while building TRT engine), I could not find any parts labeled with "myelin" in the graph.
![2022-09-14 12-10-15 的屏幕截图](https://user-images.githubusercontent.com/74638604/190057966-a6858827-91e1-4963-9b05-b2e4bd865eb8.png)
![2022-09-14 12-18-15 的屏幕截图](https://user-images.githubusercontent.com/74638604/190058492-f252b6fb-267e-4036-abd8-e0279d9d5f3c.png)

The above images shows the transformation result of a layer-norm module and partial of MHA. It seems that myelin wouldn't optimize single layer-norm block?

![2022-09-14 12-20-09 的屏幕截图](https://user-images.githubusercontent.com/74638604/190059217-d2fbdcc2-3f05-4bdd-b6bc-e992f1c0383d.png)



The third question is that the matmul with qdq inserted doesn't transformed as a int8 operator in my case. Does TRT support int8 matmul with different input scale? Or should the input scales and zero-points of both inputs be setted as the same?

Sorry for proposing so many questions……Thanks a lot for your help！

**Comment by zerollzeng** [comment]
> It seems that all the transformer layers are packaged as a single Foreign Node by Myelin. (Here is a question（**Q1**）, how could I know whether Myelin applied int8 or not?)

The foreign node has FP32 inputs and FP32 outputs, so it's computed in FP32.



> But when I replace softmax with my own manually fused DQ-IntSoftmax-Q plugin, and replace qkv-Linear+gather by detached q-Linear+k-Linear+v_Linear(since model with Gather would report error while building TRT engine), I could not find any parts labeled with "myelin" in the graph. 

Q2: That's why myelin didn't fuse those layers, as I said before it only searches and applies optimization on specific graph structures. @jackwish should know more details about it.

> The third question(**Q3**) is that the matmul with qdq inserted doesn't transformed as a int8 operator in my case. Does TRT support int8 matmul with different input scale? Or should the input scales and zero-points of both inputs be setted as the same?

How do you place the QDQ in your onnx? @ttyio for viz

**Comment by Jiang-Stan** [comment]
Thanks for you reply!

> The foreign node has FP32 inputs and FP32 outputs, so it's computed in FP32.

But I also add --fp16 and --int8 for building the engine. Is there any way for runiing the transfomer in FP16 rather than FP32?

> Q2: That's why myelin didn't fuse those layers, as I said before it only searches and applies optimization on specific graph structures. @jackwish should know more details about it.

@jackwish Hi, how do Myelin match subgraph? I thought that it is a more natural idea to synthesize subgraphs one by one and then merge them into large subgraphs, but it seems that the matching for transformer is a top-down pattern?

> How do you place the QDQ in your onnx? @ttyio for viz

As shown in this image
![2022-09-14 12-34-29 的屏幕截图](https://user-images.githubusercontent.com/74638604/190075590-0ae4e179-09aa-4c2f-aa8e-50512d482266.png)

**Comment by jackwish** [comment]
@Jiang-Stan Thank you for your patience.

> **how could I know whether Myelin applied int8 or not?)**
You don't know. But in general, if your model is _correctly_ quantized, it should run in int8.

> **Is there any way for running the transfomer in FP16 rather than FP32?**
By enabling `--fp16`, you will get the fastest kernels (either fp16 or fp32).

> **how do Myelin match subgraph?**
Myelin is a TRT component of which the behavior is not documented. The best practice is avoid depending on the undocumented behavior (because someday when upgrading TRT you will be surprised that your code not working as expected). 

Let's reinterpret it to "why TRT performs worse when inserted plugin". In general, when you inserted a plugin into the graph, it will prevent some TRT optimizations since TRT doesn't know how to optimize the plugin.

> **I noticed that TRT currently only support int8 Matmul with an constant input, as mentioned in [document](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-841/support-matrix/index.html). It seems that I need to create another Matmul Plugin.**

You can, but that depends on whether it helps with your target (which I think is for performance).

**Comment by jackwish** [comment]
@Jiang-Stan The last comment is my answers. I have two questions about your investigations of the model deployment.

What's the error you received for "replace qkv-Linear+gather by detached q-Linear+k-Linear+v_Linear(since model with Gather would report error while building TRT engine)"?

For [your post at the dev forum](https://forums.developer.nvidia.com/t/where-do-tensorrt-plugin-determine-whether-fuse-qdq-or-not/226705), what's the semantic of the `IntSoftmax`? I have not seen `IntSoftmax` in [this DeiT ONNX model](https://huggingface.co/OWG/DeiT/blob/main/onnx/model.onnx). If it's possible to represent it with operators in ONNX standand?

![](https://user-images.githubusercontent.com/4936589/191173526-a2888367-1a7d-4bd2-b0c4-652780e6f90f.png)

**Comment by Jiang-Stan** [comment]
iHi, @jackwish , thanks for your reply!
> What's the error you received for "replace qkv-Linear+gather by detached q-Linear+k-Linear+v_Linear(since model with Gather would report error while building TRT engine)"?

I'm trying to implement IntSoftmax described in I-BERT. Here is the error message I received in practice. I found that the gather operator would lead to such QDQ unpaired error report, so I replaced them. 

![image](https://user-images.githubusercontent.com/74638604/191195046-ab9f3ddf-b4f2-49f0-8e53-48556411d864.png)

> For [your post at the dev forum](https://forums.developer.nvidia.com/t/where-do-tensorrt-plugin-determine-whether-fuse-qdq-or-not/226705), what's the semantic of the IntSoftmax? I have not seen IntSoftmax in [this DeiT ONNX model](https://huggingface.co/OWG/DeiT/blob/main/onnx/model.onnx). If it's possible to represent it with operators in ONNX standand?

The qDeiT with intsoftmax can be accessed in https://forums.developer.nvidia.com/t/where-do-tensorrt-plugin-determine-whether-fuse-qdq-or-not/226705/9, named IntSoftmaxPlugin.tar (It seems that github don't support uploading .tar file)

**Comment by Jiang-Stan** [comment]
@jackwish Yes, the IntSoftmax is a pure int8 implementation. It is said that custom plugins can't be fused with DQ/Q, and I was suggested to manually remove DQ/Q fore and after intsoftmax.

**Comment by jackwish** [comment]
How this model is quantized? It seems it's missing some QDQ patterns (that's why you see the error). What if you replace the `IntSoftmax` with `Dequantize - Softmax - Quantize` pattern in the model?

**Comment by Jiang-Stan** [comment]
@jackwish If replaced the way you mentioned, the model can be correctly built by TRT engine.
I manually modified the model using graphsurgeon.

**Comment by jackwish** [comment]
Awesome! If any other issues that need to resolve? If not, we may close this issue.

**Comment by jackwish** [comment]
Close this issue since the requester can run the model now (https://github.com/NVIDIA/TensorRT/issues/2323#issuecomment-1252084472). Feel free to reopen if any further issues.
