### ISSUE TITLE
Detectron2 Panoptic segmentation to TensorRT

### ISSUE THREAD

**Issue by wartek69** [NVIDIA/TensorRT#2356]
Hi,
For my use case I'd like to speed up the Detectron2 panoptic_fpn_R_101_3x model using TensorRT.
Currently, the detection takes between 1-2sec to do predictions on a single frame. I'm using the Jetson AGX Xavier with jetpack 5.0.2.
I saw that this repo has a sample for the Detectron2 Mask RCNN R50 FPN model.
By following the guidelines from the readme of that sample I was able to transform the Mask RCNN R50 FPN model to TensorRT and ran in on the Jetson using the provided infer.py script.
After that, I tried to do the same steps using the panoptic model.
First I've transformed the model to ONNX using
```
python3 export_model.py \
	--sample-image 1344x1344.jpg \
	--config-file ../../configs/COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml \
	--export-method tracing \
	--format onnx \
	--output ./ MODEL.WEIGHTS model_final_cafdb1.pkl MODEL.DEVICE cuda
```
Take note that I did not use Caffe2 tracing. The reason for that is that Caffe2 is deprecated and not supported anymore on Detectron2, more info can be found here: https://github.com/facebookresearch/detectron2/issues/4354.
When I try to covert the generated ONNX file using the following command:
```
python3 create_onnx.py \
	--exported_onnx /home/alex/detectron2/tools/deploy/model.onnx \
	--onnx converted.onnx \
	--det2_config /home/alex/detectron2/configs/COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml \
	--det2_weights /home/alex/detectron2/tools/deploy/model_final_cafdb1.pkl \
	--sample_image /home/alex/detectron2/tools/deploy/1344x1344.jpg
```
I'm geting the following output:
```
INFO:ModelHelper:ONNX graph loaded successfully
INFO:ModelHelper:Number of FPN output channels is 256
INFO:ModelHelper:Number of classes is 80
INFO:ModelHelper:First NMS max proposals is 1000
INFO:ModelHelper:First NMS iou threshold is 0.7
INFO:ModelHelper:First NMS score threshold is 0.01
INFO:ModelHelper:First ROIAlign type is ROIAlignV2
INFO:ModelHelper:First ROIAlign pooled size is 7
INFO:ModelHelper:First ROIAlign sampling ratio is 0
INFO:ModelHelper:Second NMS max proposals is 100
INFO:ModelHelper:Second NMS iou threshold is 0.5
INFO:ModelHelper:Second NMS score threshold is 0.05
INFO:ModelHelper:Second ROIAlign type is ROIAlignV2
INFO:ModelHelper:Second ROIAlign pooled size is 14
INFO:ModelHelper:Second ROIAlign sampling ratio is 0
INFO:ModelHelper:Individual mask output resolution is 28x28
Traceback (most recent call last):
  File "create_onnx.py", line 658, in <module>
    main(args)
  File "create_onnx.py", line 637, in main
    det2_gs.update_preprocessor(args.batch_size)
  File "create_onnx.py", line 208, in update_preprocessor
    del self.graph.inputs[1]
IndexError: list assignment index out of range
```

I suppose this makes sense as the panoptic model is probably different from the Mask R-CNN R50 FPN one, but I'm not sure how to adapt the provided guidelines to apply them to the panoptic model..
That code block corresponds to filtering out the preprocessing steps, so my guess would be that needs to be adapted for this panoptic model. I'm a bit unsure how to tackle this tho. 
What would be the correct steps to convert the panoptic_fpn_R_101_3x model to TensorRT?
Hopefully, someone can assist me with it!
Br
Alex

**Comment by azhurkevich** [comment]
@wartek69 Caffe2 is still supported if you recompile PyTorch from source with BUILD_CAFFE2=1 env variable. However, yep it's just a band aid and not a good solution. Glad you were able to convert Mask R-CNN at least because with some under the hood changes in Detectron 2 converter will not work as is with latest and greatest. Node naming in caffe2/onnx graph has changed hence it won't work as is. However, it is a simple fix. I probably will not devote time to it just because at some point I'll have to remake converter purely with ONNX. 

When it comes to Panoptic stuff, there is really no easy way to do it if you go with converter and want best perf. You'll have to read original paper and understand the architecture to know what stuff to connect where like I do in my create_onnx.py. Here are some tips: understand my converter very well (read code and comments, make sure you understand it); read Panoptic paper and understand their architecture; visualize both Mask R-CNN graphs with Netron before and after the conversion to see what has been changed; when you understand what has been changed look at Panoptic ONNX graph and through obtained knowledge and trial and error try to make it work. 

You can also try just giving ONNX graph to trtexec CLI TensorRT utility and see if it will build a TensorRT engine for you, but most likely it won't work. Main reasons will be NMS op and ROIAlign op most likely, by default those ops are not yet in TRT, but are coming soon. There also may be other nodes in a NN graph, some specific ones to Panoptic model. If that is the case, you'll have to write your own TensorRT plug-in that will simulate that specific operation. Writing plug-in will require some time and some CUDA knowledge. 

You can also try other things like Torch-TensorRT or ONNX Runtime with TensorRT backend. They will not give you best perf, but you might get some speedups.

**Comment by ttyio** [comment]
closing, thanks all!
