### ISSUE TITLE
Any suggestion on how to deal with tensorflow subclassed models for QAT?

### ISSUE THREAD

**Issue by AdrianoSimonetto** [NVIDIA/TensorRT#2640]
I see that model sub-classing is not supported, and only Sequential or Functional models can be used for quantization. 
Do you have any suggestion on how to go from a sub-classed model to a sequential/functional one without redefining the whole model from scratch?

**Comment by zerollzeng** [comment]
@ttyio ^ ^

**Comment by gcunhase** [comment]
Hi @AdrianoSimonetto can you please give us more details on the Subclassed model you are trying to quantize?

The limitation involving subclassed models is due to the lack of support for those models in TensorFlow's `clone_model` function. This is being tracked in https://github.com/keras-team/keras/issues/17261, https://github.com/tensorflow/tensorflow/issues/47048, and https://github.com/tensorflow/tensorflow/issues/39856 (although they all seem to be stale).

**Comment by AdrianoSimonetto** [comment]
Hi @gcunhase, I have solved the issue by simply calling the quantization on the KerasModel that is encapsulated in our Subclassed model. Thank you anyway!

**Comment by Doomski99** [comment]
> Hi @gcunhase, I have solved the issue by simply calling the quantization on the KerasModel that is encapsulated in our Subclassed model. Thank you anyway!

Hello @AdrianoSimonetto , can you please elaborate more on how you fixed the issue?
