### ISSUE TITLE
can efficient nms trt support dynamic input shape

### ISSUE THREAD

**Issue by gaosanyuan** [NVIDIA/TensorRT#2683]
I want to know if efficient nms trt support dynamic input shape, which means that each imge may have differnet number of boxes.
if it doesn't support it, how to make the nubmer of boxes of different imges same.

Thanks

**Comment by zerollzeng** [comment]
@samurdhikaru ^ ^

**Comment by samurdhikaru** [comment]
@gaosanyuan First, I'd like to point out that TRT now has an inbuilt [INMSLayer](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_n_m_s_layer.html) in addition to the EfficientNMS plugin(s). If you are going to use the plugin instead of the inbuilt layer, I'd recommend using the [EfficientNMS_TRT](https://github.com/NVIDIA/TensorRT/blob/main/plugin/efficientNMSPlugin/efficientNMSPlugin.cpp#L300) or [EfficientNMS_Explicit_TF_TRT](https://github.com/NVIDIA/TensorRT/blob/main/plugin/efficientNMSPlugin/tftrt/efficientNMSExplicitTFTRTPlugin.cpp#L33) depending on your need. 

Both EfficientNMS plugins and `INMSLayer` supports dynamic shapes. e.g. `INMSLayer` accepts inputs with shape `[batch_size, number_boxes, 4]` or `[batch_size, number_boxes, number_classes, 4]`; what this means is that in different inference passes, the size of each input dimension can change.

If you want to have different number of boxes for each image in a single batch, you can still achieve this through the `scores` input. e.g. You can pass an input of shape `[batch_size, number_boxes, 4]` where `number_boxes` is the maximum number of boxes of any image in the batch -- have dummy boxes for images that have less than this number of boxes. Then assigns scores less than `score_threshold` for the dummy boxes, so that they will not be considered during the NMS calculation.

**Comment by gaosanyuan** [comment]
> @gaosanyuan First, I'd like to point out that TRT now has an inbuilt [INMSLayer](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_n_m_s_layer.html) in addition to the EfficientNMS plugin(s). If you are going to use a plugin instead of the inbuilt layer, I'd recommend using the [EfficientNMS_TRT](https://github.com/NVIDIA/TensorRT/blob/main/plugin/efficientNMSPlugin/efficientNMSPlugin.cpp#L300) or [EfficientNMS_Explicit_TF_TRT](https://github.com/NVIDIA/TensorRT/blob/main/plugin/efficientNMSPlugin/tftrt/efficientNMSExplicitTFTRTPlugin.cpp#L33) depending on your need.
> 
> Both EfficientNMS plugins and `INMSLayer` supports dynamic shapes. e.g. `INMSLayer` accepts inputs with shape `[batch_size, number_boxes, 4]` or `[batch_size, number_boxes, number_classes, 4]`; what this means is that in different inference passes, the size of each input dimension can change.
> 
> If you want to have different number of boxes for each image in a single batch, you can still achieve this through the `scores` input. e.g. You can pass an input of shape `[batch_size, number_boxes, 4]` where `number_boxes` is the maximum number of boxes of any image in the batch -- have dummy boxes for images that have less than this number of boxes. Then assigns scores less than `score_threshold` for the dummy boxes, so that they will not be considered during the NMS calculation.

Thanks.
I also want to know if efficient nms trt is cls_agnostic or not.
I found that two boxes of different classes have very similar box bounding. Does the plugin work as expected?

**Comment by gaosanyuan** [comment]
> @samurdhikaru Thanks for your detailed explanation.
> 
> I also want to know if efficient nms trt is cls_agnostic or not. I found that two boxes of different classes have very similar box bounding. Does the plugin work as expected? Thanks

I found the answer here: https://forums.developer.nvidia.com/t/class-agnostic-nms-plugin/237320/5

**Comment by samurdhikaru** [comment]
@gaosanyuan We will soon have class agnostic capabilities in the EfficientNMS plugin. Currently, it does not have this capability.
