### ISSUE TITLE
Please use a consistent tag style

### ISSUE THREAD

**Issue by carlosgalvezp** [NVIDIA/TensorRT#2844]
Hi, 

Currently there are 3 different tag styles:

- v8.6.0
- 8.5.3
- 22.12

This makes it very hard to automatically bump versions -  a human is required to figure out what the new tag format is every new release. Would it be possible to choose one tag format and stick to it in future releases?

Thanks!

**Comment by zerollzeng** [comment]
@rajeevsrao ^ ^

**Comment by ttyio** [comment]
Hi @carlosgalvezp , this is due to the TRT collaboration with other internal teams. 
The `v` is used to differentiate between versioned and DLFW releases.

 (For versioned we keep v prefix, but for DLFW skip it.) 
And the tags like `22.12` this is monthly release. shipped with https://docs.nvidia.com/deeplearning/tensorrt/container-release-notes/index.html

**Comment by ttyio** [comment]
@carlosgalvezp , I checked we missed monthly tag for a few release, I will raise the issue internally, to make sure that we would keep the monthly release tag for the future updates. Thanks!

**Comment by carlosgalvezp** [comment]
Sounds great, thanks a lot! Closing the issue then :)
