### ISSUE TITLE
Questions about the Reformat layer

### ISSUE THREAD

**Issue by ZhangGe6** [NVIDIA/TensorRT#2921]
Hello, I am using TensorRT on Nvidia A100, and using the fantastic [trex](https://github.com/NVIDIA/TensorRT/tree/release/8.6/tools/experimental/trt-engine-explorer) to visualize the engine graph. 

When I build the engine from resnet50, I get the plan graph with `Reformat` layers near both input and output ends (Fig. a).  Because I only care about the output of the formal part of resnet50 ([onnx model link](https://github.com/NVIDIA/TensorRT/files/11359678/L6_resnet50_rand_bias.onnx.zip)), I remove the other nodes and rebuild the engine again. However, the `Reformat` layers disappear (Fig. b).

![trt_reformat_issue](https://user-images.githubusercontent.com/63796752/235314242-6983d09b-3eba-4b20-a906-b4360a6b1577.jpg)

So I am very curious about:
1. **Why are the reformat layers inserted (in Fig. a)?** I notice that the `Reformat` layer changes the tensor format from `NCHW` and `NC/4HW4` for the following convolution layers. If the `Reformat` layers help accelerate inference, can you share some explanations/materials? 
    - I have found the [layout illustration](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#appendix) in the Nvidia official doc, but still a little confused.
    
3. **Is there a method to keep the `Reformat` layer inserting behavior consistent (between Fig. a & Fig.b)?** That is to say,  if I want to insert `Reformat` layers for the engine in Fig. b (It's better if the inserted `Reformat` layers are the same as the ones in Fig. a), how should I do?

Thanks in advance!

**Comment by zerollzeng** [comment]
Reformat layer is inserted automatically by TRT for performance or other considerations, so users don't need to worry about them, they already are in best-perf-config. 

let's take a simple example, support I have an ONNX model that has only 1 conv, and by default the input and output are NCHW, there are many conv kernels implemented in TRT, e.g. if the normal conv takes NCHW input and produces NCHW output has a perf of 100ms, but another kernel that can take NCHW input and NC/4HW4 output has a perf of 30ms, and the NC/4HW4 -> NCHW reformat only take 40ms, because 30 + 40 < 100. so TRT will choose the global best config which is the latter.

**Comment by ZhangGe6** [comment]
Got it. Thanks!
