### ISSUE TITLE
Win10 + vs2015 or vs2019 + TensorRT 7.0 + cudn9.0 link dll error

### ISSUE THREAD

**Issue by EdwardVincentMa** [NVIDIA/TensorRT#307]
![image](https://user-images.githubusercontent.com/39480728/71656818-e71cbd80-2d77-11ea-8b03-e80f2b6282d5.png)
Is this something wrong with cudnnBatchNormalizationBackwardEx？

My cudnn version is at 7.1

**Comment by rmccorm4** [comment]
Hi @EdwardVincentMa,

That pop-up box mentions you installed "TensorRT-7.0.0.11-cuda-9.0.cudnn7.6" but you say you're using cudnn 7.1 - so this is likely a version mismatch. Please upgrade to CUDNN 7.6.5 since that's what's tested per the support matrix: https://docs.nvidia.com/deeplearning/sdk/tensorrt-support-matrix/index.html
