### ISSUE TITLE
Onnx failure of TensorRTv8502.Y when running trtexec --onnx=yolo.onn --saveEngine=yolo.engine on Agx orin 64G 

### ISSUE THREAD

**Issue by powerdoudou** [NVIDIA/TensorRT#3070]
Unknown  embeded device detected, Using 59655Mib as the allocation cap for memory on embedded devices

**Comment by zerollzeng** [comment]
Looks like a new device config that is not supported by TensorRT. Will check this internally.

**Comment by powerdoudou** [comment]
> Looks like a new device config that is not supported by TensorRT. Will check this internally.

Thank you zerozero, have a nice day~

**Comment by zerollzeng** [comment]
This should be fixed in TRT 8.6, but I don't know when will the corresponding Jetpack be released.

**Comment by powerdoudou** [comment]
> This should be fixed in TRT 8.6, but I don't know when will the corresponding Jetpack be released.

This issue  just seems a bit annoying but does not affect usage. Thank you zerozero ~

**Comment by kneatco** [comment]
@powerdoudou @zerollzeng Hi all wondering if there's any confirmation that TRT 8.6 actually resolved this error or not. I would also like emphasis on @shreejalt 's question if possible please. Right now on my jetson orin agx 64gb I am also experiencing a loop of this error and it not being able to complete. Not sure if it is just going to take a very long time to complete build due to memory cap, or if it will be stuck with this warning loop forever.

**Comment by zerollzeng** [comment]
Does this happens on the latest JP release?

**Comment by shreejalt** [comment]
@kneatco I know that the warning is annoying, but models like RTDETR, YOLOv6, and all the models in mmdetection, I was able to convert. Its just that it takes somewhat long time. But whenever I try to convert YOLOv8 using ultralytics, it goes into infinite loop. I am usinf JETPACK 5.1.3(@zerollzeng )

**Comment by zerollzeng** [comment]
> I am usinf JETPACK 5.1.3(@zerollzeng ). I tried using Jetpack 6, but it does not support(or atleast it didnt back then) the paddle2onnx-gpu version. So I have to use jetpack 5.1.3

you can export the onnx in JP 5.1 and do the TRT conversion in JP 6. If it fails then it would be great if you can share the onnx model here, we can take a further check.
