### ISSUE TITLE
onnx model problem

### ISSUE THREAD

**Issue by xonobo** [NVIDIA/TensorRT#330]
[this](https://devtalk.nvidia.com/default/topic/1067980/tensorrt/onnx-model-problem-cudaactivationrunner-cpp-96-/post/5419068/#5419068) is the link to onnx model and the problems I face in loading to tensorrt 6. Strangely I can run it on tensorrt 5. 

Since I got no response from the devtalk, I want to try here.

**Comment by rmccorm4** [comment]
Hi @xonobo,

Just tried your model with TensorRT 7.0 and is worked for me:
```
$  trtexec --onnx=model0.onnx --explicitBatch
...
&&&& PASSED TensorRT.trtexec # trtexec --onnx=model0.onnx --explicitBatch
```

But it failed for TensorrRT 6.0:
```

...
[00/13/2020-21:46:09] [E] [TRT] (Unnamed Layer* 0) [Convolution]: at least 4 dimensions are required for input
While parsing node number 1 [BatchNormalization]:
ERROR: builtin_op_importers.cpp:695 In function importBatchNormalization:
[6] Assertion failed: scale_weights.shape == weights_shape
[00/13/2020-21:46:09] [E] Failed to parse onnx file
[00/13/2020-21:46:09] [E] Parsing model failed
[00/13/2020-21:46:09] [E] Engine could not be created
&&&& FAILED TensorRT.trtexec # trtexec --onnx=model0.onnx --explicitBatch

```

But if you build the OSS ONNX parser on top of TensorRT 6, it works, so this was likely found and fixed in upstream ONNX parser after the release:
```
$ nvidia-docker run -it -v ${PWD}:/mnt --workdir=/mnt nvcr.io/nvidia/tensorrt:19.12-py3
$ bash /usr/src/tensorrt/install_opensource.sh
...

$ trtexec --onnx=model0.onnx --explicitBatch
...
&&&& PASSED TensorRT.trtexec # trtexec --onnx=model0.onnx --explicitBatch
```

I believe this script (/usr/src/tensorrt/install_opensource.sh) comes with the NGC containers as of 19.12-py3, I don't think it comes with TRT6 release code. 

You can copy the script from the container, or if you don't have docker installed then you can find a similar script here: https://github.com/rmccorm4/tensorrt-utils/tree/master/OSS

**Comment by wavesCHJ** [comment]
Hi @rmccorm4 , While running the sampleOnnxMNIST.cpp, I meet this problem too, 
`WARNING: ONNX model has a newer ir_version (0.0.4) than this parser was built against (0.0.3).
[01/05/2020-23:35:15] [E] [TRT] (Unnamed Layer* 6) [Convolution]: at least 4 dimensions are required for input While parsing node number 7 [BatchNormalization]:
ERROR: builtin_op_importers.cpp:695 In function importBatchNormalization: 
[6] Assertion failed: scale_weights.shape == weights_shape`
Because I am using TensorRT6.0 by downloading the NVIDIA TensorRT in [https://developer.nvidia.com/nvidia-tensorrt-6x-download](url) and untar it directly, I can not know how to slove this problem by the way you given above. 
Can you tell me how can I slove this problem?

**Comment by rmccorm4** [comment]
@wavesCHJ something like this should work:

```
wget https://raw.githubusercontent.com/rmccorm4/tensorrt-utils/master/OSS/build_OSS.sh
source build_OSS.sh 19.12
unzip model0.onnx.zip 
trtexec --explicitBatch --onnx=model0.onnx
```

```
$ trtexec --explicitBatch --onnx=model0.onnx
...
&&&& PASSED TensorRT.trtexec # trtexec --explicitBatch --onnx=model0.onnx
```

**Comment by wavesCHJ** [comment]
Hi @rmccorm4 , thanks for your reply.
I think the build_OSS.sh script has some mistakes, such as the line 11
'git submodule update --init --recursive --progress'
I think it should be 
'git submodule update --init --recursive'

Anyway, I follow the steps in [https://github.com/NVIDIA/TensorRT/tree/release/6.0](https://github.com/NVIDIA/TensorRT/tree/release/6.0), and when git clone the TensorRT, I change it to 
'git clone -b 19.12 https://github.com/nvidia/TensorRT TensorRT'
Finally, I build the TensorRT successfully, and run the follow command successfully too:
'$ ./trtexec --explicitBatch --onnx=model0.onnx
...
&&&& PASSED TensorRT.trtexec # ./trtexec --explicitBatch --onnx=model0.onnx'

But when I test my own onnx model, it fails again:
'$./trtexec --explicitBatch --onnx=my_model.onnx
...
ERROR: /home/chenhj/TensorRT-6.0-rebuild/TensorRT/parsers/onnx/builtin_op_importers.cpp:689 In function importGather:
[8] Assertion failed: !(data->getType() == nvinfer1::DataType::kINT32 && nbDims == 1 && inputs.at(0).is_tensor()) && "Cannot perform gather on a shape tensor!"
[01/06/2020-16:22:14] [E] Failed to parse onnx file
[01/06/2020-16:22:14] [E] Parsing model failed
[01/06/2020-16:22:14] [E] Engine creation failed
[01/06/2020-16:22:14] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec # ./trtexec --explicitBatch --onnx=my_model.onnx'

Why this happen? My model can be downloaded here: [https://github.com/wavesCHJ/temp/blob/master/my_model.onnx](https://github.com/wavesCHJ/temp/blob/master/my_model.onnx)

**Comment by rmccorm4** [comment]
@wavesCHJ 

>I think the build_OSS.sh script has some mistakes, such as the line 11
>git submodule update --init --recursive --progress
>I think it should be
>git submodule update --init --recursive

`--progress` seems to be valid for git >= 2.18 per https://git-scm.com/docs/git-submodule/2.18.0

But I just removed it anyway for users with earlier versions.

---

Not sure if you're willing to upgrade, but I just ran your model with TRT 7 and it works fine, so whatever the issue was is likely fixed:

```
$ nvidia-docker run -it -v ${PWD}:/mnt --workdir=/mnt nvcr.io/nvidia/tensorrt:20.01-py3
$ trtexec --explicitBatch --onnx=my_model.onnx
...
&&&& PASSED TensorRT.trtexec # trtexec --explicitBatch --onnx=my_model.onnx
```
