### ISSUE TITLE
Python.exe - Entry Point Not Found error - cublas64_11.dll

### ISSUE THREAD

**Issue by CoolCuda** [NVIDIA/TensorRT#3439]
Hello,
I use stable diffusion on windows 10.
I can use stable diffusion UI with TensorRT without any issue.
But, eveytime I start webui-user.bat I have a serie of windows error message that I want to remove : 

Python.exe Entry Point Not Found error on dynamic link library c:\AI\venv\Lib\site-packages\nvidia\cublas\bin\cublas64_11.dll
Python.exe Entry Point Not Found error on dynamic link library c:\AI\venv\Lib\site-packages\nvidia\cudnn\bin\cudnn_adv_infer64_8.dll
Python.exe Entry Point Not Found error on dynamic link library c:\AI\venv\Lib\site-packages\nvidia\cudnn\bin\cudnn_adv_train64_8.dll
Python.exe Entry Point Not Found error on dynamic link library c:\AI\venv\Lib\site-packages\nvidia\cudnn\bin\cudnn_infer64_8.dll
Python.exe Entry Point Not Found error on dynamic link library c:\AI\venv\Lib\site-packages\nvidia\cudnn\bin\cudnn_train64_8.dll

I tried theses steps : 
- Delete venv folder
- Download dll from Nvidia site and replace them.
- Reinstall VC_redist.x64
- I tried on 2 different pc ( RTX 3060 and RTX 4090 ) they have the same errors messages.
 
If you have any idea thank you :)

**TensorRT Version**: Latest 

**NVIDIA GPU**: RTX 3060 and RTX 4090

**NVIDIA Driver Version**: 537.42

**CUDA Version**: 11, tested on 12 too

Operating System: Windows 10

Python Version (if applicable):  python: 3.10.10  

PyTorch Version (if applicable): torch: 2.0.1+cu117

**Comment by manchuwook** [comment]
<img width="308" alt="image" src="https://github.com/NVIDIA/TensorRT/assets/431161/dfd46a7a-623e-45cb-818d-3e4a9030dfc9">
<img width="311" alt="image" src="https://github.com/NVIDIA/TensorRT/assets/431161/fdcf941a-d2b4-4df8-ab69-a82e2164d29b">
<img width="309" alt="image" src="https://github.com/NVIDIA/TensorRT/assets/431161/5ea00d96-1133-4563-a20a-2273887cdacc">
<img width="309" alt="image" src="https://github.com/NVIDIA/TensorRT/assets/431161/7e31be0c-4b67-4a87-93b7-a3e7825f4280">

**Comment by CoolCuda** [comment]
yes this is the same errors as your screenshots

**Comment by zerollzeng** [comment]
@oxana-nvidia Can you kindly help here :-) I know nothing about Windows.

**Comment by Ninjapods** [comment]
I am experience the exact same errors. It happened after installing: https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT
I know if I remove the extension I won't get the errors, but I want t use the TensorRT with my RTX3060

**Comment by oxana-nvidia** [comment]
reassigning to @rajeevsrao

**Comment by rajeevsrao** [comment]
TensorRT 9.x requires cudnn and cublas installed on the system. On Windows, pytorch comes bunded with (a potentially different version of) cudnn which could (depending on relative load order of torch and tensorrt) result in symbol conflicts with the cudnn package installed by using package manager (pip or conda). This will be fixed in TensorRT 10.0.

To work around this issue in the meantime:
1) If pytorch is installed in and is imported by your project, uninstall the system cudnn package after installing TensorRT. Example: https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/blob/main/install.py#L12-L14
2) Import TensorRT before Torch. Example: https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/blob/main/utilities.py#L32-L33

**Comment by ttyio** [comment]
closing since there is already WAR, thanks all!
