### ISSUE TITLE
tiny_yolov2 The caffe parser cannot parse the last region. An error occurred Message type "ditcaffe.LayerParameter" has no field named "region_param".

### ISSUE THREAD

**Issue by maidouxiaozi** [NVIDIA/TensorRT#346]
## Environment

**TensorRT Version**: 
**GPU Type**: 
**Nvidia Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System + Version**: 
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by maidouxiaozi** [comment]
Time is urgent thank you

**Comment by rmccorm4** [comment]
Hi @maidouxiaozi,

1. Please fill in the environment information and how to reproduce your issue, it's difficult to help without it.
2. Is it possible to use an ONNX model instead of a Caffe model? The Caffe parser will be deprecated in the future
3. This is likely from a custom model or an unsupported layer or something. Please provide more context on the error and how to reproduce it.

**Comment by maidouxiaozi** [comment]
ubuntu16.04 cuda10.0 cudnn7.4 tensorrt7
It is the last layer of the tiny_yolov2 prototxt file is the region layer, and then the tensorrt7 caffe parser cannot resolve the lowest layer region, and the problem of no region_pram occurs. Then see that the tensorrt official website supports the region layer.
I don't have a custom model

**Comment by rajeevsrao** [comment]
@maidouxiaozi is it possible for you to move your workflow to ONNX? There is a tiny yolov2 model on the ONNX modelzoo: https://github.com/onnx/models. Our caffe parser is in maintenance mode and will not be supported except for critcial bugfixes.
