### ISSUE TITLE
What does explicit and implicit batch mean ?

### ISSUE THREAD

**Issue by wwdok** [NVIDIA/TensorRT#4148]
I don't quite understand what "explicit" and "implicit" mean in the context of TensorRT. 
My understanding is that explicit batch means fixed batch size, e.g.  (4,3,256,256). Implicit batch means dynamic batch size, e.g. (-1,3,256,256) .
Is my understanding correct? If not, what is the correct explanation?

**Comment by lix19937** [comment]
Explicit batch is required when you are dealing with Dynamic shapes, otherwise network will be created using implicit batch dimension.

In implicit batch mode, every tensor has an implicit batch dimension and all other dimensions must have constant length. This mode was used by early versions of TensorRT, like trt5.x.
﻿
In explicit batch mode, all dimensions are explicit and can be dynamic, that is their length can change at execution time. Many new features, such as dynamic shapes and loops, are available only in this mode.

**Comment by wwdok** [comment]
Oh, it seems I didn't understand correctly. I haven't used the older version of TensorRT 5.x. Let me explain my latest understanding. For example, an image tensor with four dimensions, namely (n, c, h, w), is explicit. If it has three dimensions, namely (c, h, w), then it is implicit. Is this understanding correct?

**Comment by lix19937** [comment]
There is one thing that needs to be corrected:

First we consider a network that processes N images of size HxW with 3 channels in NCHW format.  

At runtime, the input tensor has dimensions [N,3,H,W]. The two modes differ in how the INetworkDefinition specifies the tensor's dimensions:   

The network specifies [N,3,H,W] in explicit batch mode.    
The network specifies only [3,H,W] in implicit batch mode. The batch dimension N is implicit.
