### ISSUE TITLE
Any clean minimal example code to show how to use TensorRT cpp api to do inference after I got the searilized engine?

### ISSUE THREAD

**Issue by Edwardmark** [NVIDIA/TensorRT#453]
Any clean minimal example code to show how to use TensorRT cpp api to do inference after I got the searilized engine?

I could not found any simple clean code to follow.
Please help me out.
Thanks.

**Comment by rmccorm4** [comment]
Hi @Edwardmark ,

Serializing an engine: https://github.com/NVIDIA/TensorRT/blob/9d37f5df73096b533442d2e9a7713c16f801d13a/samples/common/sampleEngines.cpp#L518-L536

Deserializing an engine: https://github.com/NVIDIA/TensorRT/blob/9d37f5df73096b533442d2e9a7713c16f801d13a/samples/common/sampleEngines.cpp#L488-L516

Simple inference on a engine created from a network with EXPLICIT_BATCH (note it uses `executeV2` with no batch_size parameter instead of `execute`): https://github.com/NVIDIA/TensorRT/blob/9d37f5df73096b533442d2e9a7713c16f801d13a/samples/opensource/sampleDynamicReshape/sampleDynamicReshape.cpp#L234-L265

Simple inference on an engine created from an implicit batch network (no EXPLICIT_BATCH) - (note it uses `enqueue` WITH a batch_size parameter instead of `enqueueV2`: https://github.com/NVIDIA/TensorRT/blob/master/samples/opensource/sampleMNIST/sampleMNIST.cpp#L276-L325

Hope this helps. It's worth looking around the sample code a bit and piecing together the parts you want.

**Comment by Edwardmark** [comment]
@rmccorm4 Thank you very much. It helps a lot.

**Comment by Edwardmark** [comment]
@rmccorm4 How to do inference using fp16? I create my engin file using torch2trt in fp16 mode, my code to do fp16 inference is as below, is that right? I cannot find any sample code to using image as input to do fp16 inference. Thanks in advance.
https://github.com/Edwardmark/dog_classification/blob/master/test.cpp

**Comment by siquike** [comment]
This is helpful, but how do you navigate the dependency hell of compiling and linking tensorRT? It would be helpful if I could just use a single dynamic library in my CMakeLists.txt. Is there a simple Cmake example for tensorRT that includes how to use the logger etc (in common directory)? I just want to use it in my own project. Thanks

**Comment by sujoyrc** [comment]
@rmccorm4 I am trying to follow the FRCNN inference given in 

https://github.com/NVIDIA/TensorRT/blob/master/samples/opensource/sampleFasterRCNN/sampleFasterRCNN.cpp 

and am doing batch inference for batch sizes between 1 to 4 .  As per TensorRT documentation the inference time should remain roughly constant but it is increasing almost linearly.

Is the code in between lines 285-293 in the above link also valid for batch inference ? 

I have run it on two different GPU machines and here are the runtimes I observe

Machine 1 :  - Tesla P100 GPU with 64 GB CPU RAM 

Batch size       Inference Time
=========================
1                      27
2                      49
4                      91

Machine 2 :-   GEForce RTX 2070 Super with 32 GB CPU RAM

Batch size       Inference Time
=========================
1                      16
2                      28
4                      48

Can you please advice if I am doing something wrong.
