### ISSUE TITLE
5-dim is supported for tensorrt?

### ISSUE THREAD

**Issue by zh199110** [NVIDIA/TensorRT#454]
my input tensor is 5-dims! 
Assertion failed: onnx_padding.size() == 8 && onnx_padding[0] == 0 && onnx_padding[1] == 0 && onnx_padding[4] == 0 && onnx_padding[5] == 0 && "This version of TensorRT only supports padding on the outer two dimensions on 4D tensors!"

**Comment by JingyuQian** [comment]
I belive max dims supported is 8 in the latest version of TensorRT. The following is from `NvInferRuntimeCommon.h` file:
```cpp
class Dims
{
public:
    static const int MAX_DIMS = 8; //!< The maximum number of dimensions supported for a tensor.
    int nbDims;                    //!< The number of dimensions.
    int d[MAX_DIMS];               //!< The extent of each dimension.
    TRT_DEPRECATED DimensionType type[MAX_DIMS];  //!< The type of each dimension.
};
```
Regarding your problem it's probably related to the padding behavior rather than general tensor dimensions.

**Comment by azad96** [comment]
@zh199110  I also get the "Assertion failed: onnx_padding.size() == 8" error. Did you find a solution?

**Comment by shuo-zhao** [comment]
Hi, 
I got the same problem when I transed a onnx model to tensorrt. And the problem is when I got a onnx model, it has a padding layer which use to add channels. The padding layer runs well with onnxruntime but is not supported in tensorrt and get the same error: 
Assertion failed: onnx_padding.size() == 8 && onnx_padding[0] == 0 && onnx_padding[1] == 0 && onnx_padding[4] == 0 && onnx_padding[5] == 0 && "This version of TensorRT only supports padding on the outer two dimensions on 4D tensors!"

How can I use a channel padding layer in tensorrt or how can I change the padding layer?
Thanks!

**Comment by shuo-zhao** [comment]
Could anyone tell me how to fix it? 
Thannx a lot!

**Comment by shuo-zhao** [comment]
Hello?

**Comment by kevinch-nv** [comment]
In TensorRT, we only support padding on the outer 2 dimensions of a tensor. How are you padding your input tensor?

**Comment by ttyio** [comment]
I will close this since no response for more than 3 weeks, please reopen if you still have question, thanks!
