### ISSUE TITLE
How to manage the GPU memory and Host Memory? Especially release to OS

### ISSUE THREAD

**Issue by VCBE123** [NVIDIA/TensorRT#530]
My environment is 

Linux: 18.04  GTX 2080Ti TensorRT 7.0 C++  Pytorch1.14 Onnx1.6 CUDA10 CUDNN7.6
Windows 10 x64, GTX1650Ti,TensorRT 7.0 C++ Pytorch1.14 Onnx1.6 CUDA10 CUDNN7.6

I convert PyTorch model( Efficientnet-b2 about 30M) to ONNX model then serialized to an engine file and reload using tensorRT 7.0 C++.
The program cost about 2G host memory and 631M GPU memory. However，after I finish the inference and destroy the runtime, context, and engine. The program does not release the resource to the Operator System. 
What's the proper way to manage the resource,  May I allocate the host memory in Memory Pool? 

I read the TensorRT document and find the IGpuAllocator maybe a method to manage the GPU resource but it's not quite clear for me. 

I also read the buffers.h in the samples code, May I use this  BufferManager to solve the issue above?

**Comment by rmccorm4** [comment]
I would refer to these sections of the docs: https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#mem_management_c and https://docs.nvidia.com/deeplearning/sdk/tensorrt-best-practices/index.html#memory

**Comment by VCBE123** [comment]
> I would refer to these sections of the docs: https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#mem_management_c and https://docs.nvidia.com/deeplearning/sdk/tensorrt-best-practices/index.html#memory
> 
> Other than that, the regular rules for C++ memory management should apply as usual.

Thank you very much for your answer, can you give me a feasible example, that would be of great help.

**Comment by ttyio** [comment]
Hello @VCBE123 , thanks for reporting

sample code for the usage of gpu allocator
https://github.com/NVIDIA/tensorrt-laboratory/blob/33b6fdf2935cd49944ae7d16601cc58f6199cd49/trtlab/tensorrt/include/trtlab/tensorrt/allocator.h

FYI, you cannot reduce the memory footprint to the model size, because tensorrt use cudnn/cublas, and after the first API call into these library, the CPU/GPU memory used for the kernels will not return to operation system unless unload the cudnn/cublas library. So my suggestion is that run `cudnnCreate` and `cublasCreate` on your system first, to see the gap between 631M and reported value, then to decide if you want to put your effort on implementing custom gpu allocator.

**Comment by ttyio** [comment]
I will close since get no response for more than 2 weeks, please reopen if you still have question, thanks!
