### ISSUE TITLE
how can i Use Tensor Cores to infer when i use TRT?

### ISSUE THREAD

**Issue by jlygit** [NVIDIA/TensorRT#54]
hi,
how can i Use Tensor Cores to infer when i use TRT?

does it supports  single precision (FP32)?

thks

**Comment by rmccorm4** [comment]
@CMagWheels is right - there are also some hardware requirements in order to make use of Tensor Cores, see the support matrix for that here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-support-matrix/index.html#hardware-precision-matrix, specifically the "FP16 Tensor Cores" and "INT8 Tensor Cores" columns.
