### ISSUE TITLE
speed of int8 model is slower than fp16 model

### ISSUE THREAD

**Issue by yflv-yanxia** [NVIDIA/TensorRT#550]
## Description
I used peleenet as backbone for object detection, peleenet is same as [peleenet](https://github.com/Robert-JunWang/PeleeNet)
I converted the model to tensorrt int8 model and tensorrt fp16 model and figured out the speed of int8 model is slower than fp16 model, is it reasonable?

## Environment
**TensorRT Version**:  6.0.1.5
**GPU Type**: titan rtx
**Nvidia Driver Version**:  418.74
**CUDA Version**:  libcudart.so.10.0.130
**CUDNN Version**: libcudnn.so.7.6.3

**Comment by rmccorm4** [comment]
Hi @yflv-yanxia ,

How did you convert your model to fp16 and int8?

For converting to fp16, you should enable the `fp16` builder flag.

For converting to int8, you should enable **both the `fp16` and `int8` builder flags**. This way, if an int8 op is too slow or unsupported, in can fall back to an fp16 op instead of falling back to an fp32 op.

**Comment by ttyio** [comment]
Close since get no response for more than month, @yflv-yanxia please reopen if you still have issue, thanks!
