### ISSUE TITLE
tensorrt7 use 2x more gpu memory than tensorrt4

### ISSUE THREAD

**Issue by HaoLiuHust** [NVIDIA/TensorRT#565]
## Description

I am transforming my tensorrt4 application to tensorrt7, however, I found that when running a same model, tensorrt7 use 2 times gpu memory compared to tensorrt4.

## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: 1080TI
**Nvidia Driver Version**: 
**CUDA Version**: CUDA10.2
**CUDNN Version**: 7.6.5
**Operating System + Version**: Ubuntu 16.04
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by ttyio** [comment]
Hello @HaoLiuHust , thanks for the question.
there is a space-memory tradeoff, Have you tried change to a smaller workspace size when build the engine, to see if this helps. If you still not satisfy on the memory consumption. Could you share your model so that we can do a further analysis to see if the extra memory is reasonable? Thanks.
