### ISSUE TITLE
ERROR: The engine plan file is not compatible with this version of TensorRT, expecting library version 5.1.5 got 0.0.0, please rebuild.

### ISSUE THREAD

**Issue by azuredsky** [NVIDIA/TensorRT#574]
![1590559985(1)](https://user-images.githubusercontent.com/3139866/82984594-0ff26780-a025-11ea-9032-638e02237120.jpg)

## Environment

**TensorRT Version**:  5.1.5.0
**GPU Type**: GTX1080Ti
**Nvidia Driver Version**: 445.75
**CUDA Version**: 10.0
**CUDNN Version**: 7.5.1 , also try 7.6.5
**Operating System + Version**: windows 10

Loading TRT Engine...
ERROR: The engine plan file is not compatible with this version of TensorRT, expecting library version 5.1.5 got 0.0.0, please rebuild.
Loading Complete!

I seralizing the plan file and load it at the same time why it's not compatible ?

std::cout << getInferLibVersion() << std::endl;
nvinfer1::IRuntime* runtime = nvinfer1::createInferRuntime(logger);  error in here

I use code from : https://github.com/CaoWGG/TensorRT-YOLOv4 and change it for windows

**Comment by azuredsky** [comment]
I had solved it， in writePlanFileToDisk()  function seralizing the plan file with the code：
`outFile.open(m_EnginePath, std::ios::binary | std::ios::out);`
and in the loadTRTEngine as the code:
    std::ifstream cache(planFilePath, std::ios::binary | std::ios::in);

then it solved.

**Comment by uRENu** [comment]
In my case: 
If I use the TFT optimization model through the following methods：
      
`import tensorflow as tf
import os
import shutil
from tensorflow.python.compiler.tensorrt import trt_convert as trt

input_saved_model_dir = '/root/check2PB/test/1'
output_saved_model_dir = '/root/check2PB/trt/3'

if os.path.exists(output_saved_model_dir):
    shutil.rmtree(output_saved_model_dir)
    
converter = trt.TrtGraphConverter(
    input_saved_model_dir=input_saved_model_dir,
    precision_mode="FP16")
converter.convert()
converter.save(output_saved_model_dir)`
      
messege get:
INFO:tensorflow:Linked TensorRT version: (5, 1, 5)
INFO:tensorflow:Loaded TensorRT version: (5, 1, 5)
INFO:tensorflow:Running against TensorRT version 5.1.5
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
INFO:tensorflow:The specified SavedModel has no variables; no checkpoints were restored.
INFO:tensorflow:Froze 0 variables.
INFO:tensorflow:Converted 0 variables to const ops.
INFO:tensorflow:No assets to save.
INFO:tensorflow:No assets to write.
INFO:tensorflow:SavedModel written to: /root/check2PB/trt/3/saved_model.pb     
      
     
when i test the output_saved_model ('/root/check2PB/trt/3'), an error is reported：  

ERROR: The engine plan file is not compatible with this version of TensorRT, expecting library version 5.0.6 got 5.1.5, please rebuild.    


But If I use the TFT optimization model through the following methods：  

docker run --rm --runtime=nvidia -it -v /root:/tmp tensorflow/tensorflow:1.15.0-gpu-py3 /usr/local/bin/saved_model_cli convert --dir /tmp/check2PB/test/1 --output_dir /tmp/check2PB/trt/3  --tag_set serve tensorrt --precision_mode FP32 --max_batch_size 1 --is_dynamic_op True

no error reported.

It seems that the tensorRT version and tensorflow version do not correspond.
