### ISSUE TITLE
trtexec usage about --loadInputs

### ISSUE THREAD

**Issue by WangXuanBT** [NVIDIA/TensorRT#617]
Hi everyone,
About trtexec, can any one show a sample usage about the param --loadInputs?
I found someone use the command like:
trtexec --onnx=test.onnx --dumpOutput --batch=1 --safe --loadInputs=Input:input.txt
but he didn't explain where the input.txt is and its data format.
Thank you.

**Comment by CallmeZhangChenchen** [comment]
This should be the value of the incoming network，

Load input values from files (default = generate random inputs). Input names can be wrapped with single quotes (ex: 'Input:0')
                              Input values spec ::= Ival[","spec]
                                           Ival ::= name":"file

**Comment by rmccorm4** [comment]
Hi @WangXuanBT ,

I believe `input.txt` is just a binary file of the raw data. Since `trtexec` is generally used for benchmarking, people generally just use random data. If you wanted to test on real data, I suggest writing a short script using the TensorRT C++/Python APIs directly - this way you can handle all of the necessary pre-processing and post-processing as need be.

**Comment by 14asaf** [comment]
Is there new?
