### ISSUE TITLE
How to debug if inferance with TensorRT 

### ISSUE THREAD

**Issue by daydayfun** [NVIDIA/TensorRT#636]
I run resnet50 with TensorRT and the accurancy descends by 5%, How to debug with the acc problem?

**Comment by rmccorm4** [comment]
Hi @daydayfun ,

You can iteratively mark intermediate tensors throughout the TensorRT INetworkDefinition as outputs in order to see their values, and compare these with the layerwise outputs of the original model to see at which point the compared values start to diverge between the original model and TensorRT engine.

**Comment by ttyio** [comment]
Close since we already answered and there is no activities in the past 3 weeks, please create another issue if you still have problems, thanks!
