### ISSUE TITLE
--best feature generated mixprecision model drop rapidly on mAP

### ISSUE THREAD

**Issue by jinfagang** [NVIDIA/TensorRT#687]
Hi, when I execute `trtexec` converting onnx model to trt engine, the generated engine file are smaller and speed almost half, so I suppose it actually did mixed precision on model. 

However, the generated model performance much more worse than original. the command I am runing were:
```
 trtexec --onnx=v1_sim.onnx --best  --saveEngine=v1_v1.engine
```

Here is my question:

1. I am not send any calibration file how does it do quantization?
2. What else params I need to get such a `best` model? (I mean both speed and accuracy)

**Comment by rmccorm4** [comment]
Hi @jinfagang ,

I believe `--best` is equivalent to `--fp16 --int8`, and `trtexec` uses random data for `int8` calibration as you've guessed, as it's meant simply for quick testing and benchmarking. 

You'd want to write your own calibrator class and feed it your own calibration data if you want the benefits of potential INT8 speedup while maintaining close to original model accuracy. Otherwise you'd probably just want `trtexec --fp16 --explicitBatch --onnx=model.onnx`

**Comment by jinfagang** [comment]
@rmccorm4 I simply using a command line tool `trtexec`, does there any proper way for me to add such a calibrator class? If am not remember wrong, original onnx2trt tools also have a int8 option, What's the difference between them?

**Comment by rmccorm4** [comment]
You can think of `trtexec` as basically a superset of `onnx2trt`, likely with some minor differences. Out of the two choices, `trtexec` is preferred. Either way, if you want to do INT8 for anything more than benchmarking, you'll need to use the Python or C++ TensorRT API to implement a calibrator. If you are only interested in FP32/FP16, then tools like `trtexec` should be sufficient on their own.

**Comment by mk-nvidia** [comment]
Closing due to no response from the issue reporter.
