### ISSUE TITLE
Batch inference timings increasing almost linearly

### ISSUE THREAD

**Issue by sujoyrc** [NVIDIA/TensorRT#739]
## Description  

In NVIDIA documentation https://docs.nvidia.com/deeplearning/tensorrt/best-practices/index.html#batching it is stated 

"Larger batch sizes are almost always more efficient on the GPU. Extremely large batches, such as N > 2^16, can sometimes require extended index computation and so should be avoided if possible. Often the time taken to compute results for batch size N=1 is almost identical to batch sizes up to N=16 or N=32"

However we are not observing constant run times even for N=1 to 4

## Environment

**TensorRT Version**: 
**GPU Type**: See below 
**Nvidia Driver Version**: 
**CUDA Version**: 11.0
**CUDNN Version**: 8.0.0
**Operating System + Version**:  Ubuntu 18.04
**Baremetal or Container (if container which image + tag)**: container -  nvcr.io/nvidia/tensorrt:20.06-py3

I am trying to follow the FRCNN inference given in

https://github.com/NVIDIA/TensorRT/blob/master/samples/opensource/sampleFasterRCNN/sampleFasterRCNN.cpp

and am doing batch inference for batch sizes between 1 to 4 . As per TensorRT documentation the inference time should remain roughly constant but it is increasing almost linearly.

Is the code in between lines 285-293 in the above link also valid for batch inference ?

I have run it on two different GPU machines and here are the runtimes I observe

Machine 1 : - Tesla P100 GPU with 64 GB CPU RAM

Batch size Inference Time
1 27
2 49
4 91

Machine 2 :- GEForce RTX 2070 Super with 32 GB CPU RAM

Batch size Inference Time
1 16
2 28
4 48

Can you please advice if I am doing something wrong.

We have observed similar performance even with Yolov4 model. Also nothing else is running on either of the machines when the inference is happening.

**Comment by mk-nvidia** [comment]
@sujoyrc Which TensorRT version are you hitting this with?

**Comment by sujoyrc** [comment]
@mk-nvidia TensorRT version 7.1.2

**Comment by lowsfer** [comment]
That statement is not always true.
"Often the time taken to compute results for batch size N=1 is almost identical to batch sizes up to N=16 or N=32"
This statement is removed from the newest guide.

It applies to a some layers, e.g. Fully-connected, where the most cost is on reading weights rather than computation. N=1 and N=16 needs to read the same amount of weights.
It also applies to some special cases:
Tensors are very small but the GPU is big. In this case, N=1 cannot even give each SM one thread block, and increasing batch size may not cost more time before assigning each SM at least one thread block.

In general cases, that statement does not apply.

**Comment by mk-nvidia** [comment]
Closing due to no response from bug reporter.
