### ISSUE TITLE
IBuilder::setMaxWorkspaceSize() is not effective

### ISSUE THREAD

**Issue by LitLeo** [NVIDIA/TensorRT#749]
## Description

I'm building a large float32 model using API mode with static input shape.
This model has more than 100 layers and a large input shape. So it costs a lot of GPU memory.

When I set MaxWorkspaceSize = 10G, it's ok with maxBatchSize[1-6]. But when the maxBatchSize=7, error happens as follows.
```
[08/18/2020-19:07:36] [W] [TRT] GPU memory allocation error during getBestTactic: 9_full_with_bias
[08/18/2020-19:07:36] [E] [TRT] Internal error: could not find any implementation for node 9_full_with_bias, try increasing the workspace size with IBuilder::setMaxWorkspaceSize()
```
I search the error, and find this happens due to the lack of workspace size. ButI increase the MaxWorkspaceSize to 20G, the error sitll here. Why?  Is this a bug or something?

## Environment

**TensorRT Version**: TensorRT-7.0.0.11
**GPU Type**: Tesla P40
**Nvidia Driver Version**:  418.116.00
**CUDA Version**: cuda 9.0
**CUDNN Version**: 7.6.4
**Operating System + Version**: CentOS Linux release 7.2 (Final)
**Python Version (if applicable)**: 
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by LitLeo** [comment]
And when I set MaxWorkspaceSize = 10G and maxBatchSize=6, same error happens. Why？ It's weird！

**Comment by mk-nvidia** [comment]
@LitLeo Do you face the same error with TensorRT-7.1? Can you share a repro case/representative model that we can use to investigate the error at our end? Thanks

**Comment by baskervill** [comment]
Can you try  IBuilderConfig::setMaxWorkspaceSize instead of IBuilder? "IBuilder::setMaxWorkspaceSize()  API will be removed in a future release, use IBuilderConfig::setMaxWorkspaceSize instead." since 6.0, quote from doc https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_builder.html.

**Comment by DilipSequeira** [comment]
The documentation here could be clearer. Here's what it says:

_Some TensorRT algorithms require additional workspace on the GPU. The method `IBuilderConfig::setMaxWorkspaceSize()` controls the maximum amount of workspace that may be allocated, and will prevent algorithms that require more workspace from being considered by the builder._

i.e. `maxWorkspaceSize` is the discretionary memory that the user provides TensorRT to use as scratch space for some of the algorithms that make aggressive speed/space tradeoffs in favor of speed - it doesn't include activation memory, nor does it include weight memory.

My guess is what's happening is that TensorRT is allocating 10GB of memory for scratch, then the TensorRT optimizer doesn't have enough space to optimize the network, since it has to fit the activations and weights in the remaining space.

10GB may be way more than you need. I'd suggest trying with 1GB and seeing if you see any perf regressions on your smaller cases (using smaller scratch may exclude some algorithm choices.) If you do, increase the memory 'til performance is back.
