### ISSUE TITLE
How can I use tensorRT in 3D image including hight, width and depth

### ISSUE THREAD

**Issue by PengfeiGo** [NVIDIA/TensorRT#79]
Hi ,
   I have a tensorflow-trained 3D network---V-Net, which is a 3D segmentation  network. That means the input and output image  is a 3D image including hight, width and depth. I notice that the tensorRT API UffInputOrder has three members:NC, NHWC, NCHW. All of them are for 2D image.
   So how can I use tensorRT in my 3D V-Net model?
   Thanks

**Comment by Rongnian** [comment]
TensoRT only supports 2D convolution.
[https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#convolution-layer](url)

**Comment by Rongnian** [comment]
> Hi ,
> I have a tensorflow-trained 3D network---V-Net, which is a 3D segmentation network. That means the input and output image is a 3D image including hight, width and depth. I notice that the tensorRT API UffInputOrder has three members:NC, NHWC, NCHW. All of them are for 2D image.
> So how can I use tensorRT in my 3D V-Net model?
> Thanks

Now TensorRT 6.0 supports conv3D.

**Comment by rmccorm4** [comment]
@Rongnian is correct. And if you experience issues with the UFF parser, I would recommend exporting your model to ONNX and trying the ONNX parser instead like here: https://github.com/NVIDIA/TensorRT/issues/185. 

If you experience this error (https://github.com/NVIDIA/TensorRT/issues/180), it should be fixed in the next release.
