### ISSUE TITLE
TF-ONNX-TRT workflow: INT8 calibration, get dynamic range during training?

### ISSUE THREAD

**Issue by carlosgalvezp** [NVIDIA/TensorRT#811]
Hi,

I would like to do INT8 calibration without using TensorRT to compute the dynamic range, for a number of reasons. Instead, I would like to compute statistics at training time in TF (since then we actually get to see ALL the data, not just 500 images) and then pipe that to TensorRT.

The problem is that the pipeline is quite involved: TF -> ONNX -> TRT, and in the process the original TF layers are optimized away, fused, broken down into smaller layers, etc etc.

So my question: how can I accomplish this in practice? Even if I get the dynamic range for TF layers, it will be useless for TRT layers, since they will be different.

This is not a TRT bug per se, but I wanted to ask in case someone has come across the problem and solved it in a nice way.

**Comment by ttyio** [comment]
Hello @carlosgalvezp , thanks for your question.

In TensorRT we provide 2 ways for customer to provide the `int8` dynamic range:

- Using the `setDynamicRange` https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_tensor.html#a956f662b1d2ebe7ba3aba3391aedddf5
- Using the calibration cache https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleINT8#calibration-file

And you are right, it is hard to mapping the layer names because it is a long path from `TF->ONNX->TRT`, and the `ONNX->TRT` is not a 1:1 mapping, some ONNX operator may translated into multiple TRT operator, and might fused with other operators in TRT.

So far I do not know if there is any sample that we can follow. And my suggestion might enable the `verbose` log in TRT,  use your favorite tool to visualize the TF file and ONNX file, and try to align all the 3 of them together. Finally update the scales in the calibration cache or using the `setDynamicRange` API.

Good luck~

**Comment by ttyio** [comment]
Close since no response for more than 2 weeks, please reopen if you have more questions, thanks!
